### ISSUE TITLE
Use Moo instead of Moose

### ISSUE THREAD

**Issue by ferki** [RexOps/Rex#1003]
Moose has been added as a dependency on #996. Moo was considered as a primary choice for an OO system based on previous discussions, as is is much more lightweight so it might be easier to package too (fixme). It's also compatible with Moose, so I guess the conversion is easy.

**Comment by krimdomu** [comment]
Hi ferki,

first i used Moo for the Resources but then i saw that Moo doesn't have an `override` method. The author sais that one should use `around` to do this, but i don't like this.

A second thing is that with Moo we don't have type checking included and i think integrated typechecking is a cool thing.

I already use Moose for the rex-application and other modules and i don't have any performance issues with it.

Also we already have packages for Moose.

**Comment by ferki** [comment]
Thanks for the explanation!
