### ISSUE TITLE
Ubuntu packages

### ISSUE THREAD

**Issue by johscheuer** [RexOps/Rex#1007]
Hi,

I wanted to ask if it's planned to build packages for `Vivid`,`Wily`and `Xenial`. I couldn't find any packages for these releases on https://rex.linux-files.org/ubuntu/dists

Thanks!

**Comment by krimdomu** [comment]
Hi @johscheuer 
currently we're only building packages for ubuntu lts versions. Since ubuntu is shipping rex itself maybe it would be good to also build packages for non-lts versions, so that users can update their rex package.

**Comment by ferki** [comment]
I just checked and it looks like current LTS versions (`12.04` and `14.04`) of Ubuntu doesn't ship with rex (16.04 will ship rex-1.3.3). So building rex packages for LTS Ubuntu versions still would make sense.

On top of that, I think it's a good idea to try to build packages for any Ubuntu versions that is still supported by their upstream (=Canonical). This would mean `15.10 Wily` as of now, but not `15.04 Vivid` (EOL 2016-02-04).

I can generate a 15.10 virtual machine easily on build.rexify.org to help with packaging.

**Comment by johscheuer** [comment]
closing this one :)
