### ISSUE TITLE
Net::SSH2 0.59 compatibility changes

### ISSUE THREAD

**Issue by krimdomu** [RexOps/Rex#1023]
As salva on irc mentioned, with Net::SSH2 0.59 there will be some changes. We need to find out what code parts we need to change so that Rex works with the new version and also with old ones.

- [x] passing options to connect is deprecated at Rex::Interface::Connection::SSH.pm line 79 (and timeout uses wrong unit, should be passed in milliseconds) -> fixed in `net-ssh2-compat-#1023` branch
- [x] ~~`key_auth` is not working with Net::SSH2-0.59_10~~ false report
- [x] `rex -d` reports ` Found Net::OpenSSH and Net::SFTP::Foreign - using it as default` even if `set connection => 'SSH'` is set (and it is really using Net::SSH2)
- [x] rex hangs at shell detection on executing `version` (for idrac shell detection) as a non-existing command with Net::SSH2-0.59_10: printing to remote STDERR causes the hang -> possible regression in Net::SSH2: rkitover/net-ssh2#32 (or rex retrieves STDOUT/STDERR in a problematic way)

**Comment by ferki** [comment]
If it's a bigger change (i.e. slow to actually be released), we can try to temporarily state required Net::SSH2 version in dist.ini too.

**Comment by salva** [comment]
The changes in Net::SSH2 has been mostly internal: refactoring and clean up. It may introduce some minor backward incompatibilities in edge cases, but you may well be unaffected by them. Actually, my expectation is to break mostly code that has workarounds for Net::SSH2 issues now solved!

In my opinion, the first step should be to just test Rex using the development version of Net::SSH2 in your supported configurations and report any issue you find as Net::SSH2 bugs. From there we would investigate and plan how to fix them in the best manner.

**Comment by ferki** [comment]
Thanks for the heads-up, @salva! I've installed Net::SSH2-0.59_10, and will test it with my usual cases. I'll report any findings, but feel free to ping us again before you'd like to release the final version.

I just found one deprecated usage on the Rex side, I'll update the opening comment with that.

**Comment by salva** [comment]
My plan now is to focus on fixing any bugs reported, keeping releasing new developer versions until it stabilizes. Then, the stable version (0.60) would be released. But I am flexible here and can synchronize with you if that makes your lives easier.

**Comment by ferki** [comment]
I've opened `net-ssh2-compat` branch to track progress. I already fixed some minor stuff there.

@salva: I think we can update everything for our upcoming release, probably before Net::SSH2-0.60 (or we can do a bugfix release soon after 0.60 if needed).

**Comment by ferki** [comment]
rkitover/net-ssh2#32 is fixed, rex behaviour with 0.59_11 is the same as with 0.58. So strictly speaking it's not a compatibility issue anymore, but the parallel draining should be fixed for Net::SSH2 too (I'll open a separate issue for that).

**Comment by krimdomu** [comment]
This isn't done yet.
For example when i run integration test "tests/file_with_spaces.rex" i get a lot of `Use of uninitialized value in subroutine entry at /home/jan/Projekte/rex/rex/lib/Rex/Helper/File/Stat/Unix.pm line xx.`
