### ISSUE TITLE
Error in Documentation "Rex::Commands::File"

### ISSUE THREAD

**Issue by LeMerP** [RexOps/Rex#1034]
Hi guys,

I found an documentation error here:
URL: http://rexify.org/docs/api/1.4/rex/commands/file.pm.html#file_read-file_name-
Section:
```
 task "read-passwd", "server01", sub {
   my $fh = file_read "/etc/passwd";
   for my $line = ($fh->read_all) {
     print $line;
   }
   $fh->close;
 };
```

for my $line = ($fh->read_all)
should be:
foreach my $line ($fh->read_all)

Regards

**Comment by ferki** [comment]
@LeMerP: good catch, thanks!
