### ISSUE TITLE
Logger.pm - uninitialized value $host

### ISSUE THREAD

**Issue by stiron** [RexOps/Rex#1051]
This is Rex version: 1.4.0

The logger class cannot put the target hostname in particular situations. I did not have enough time to deep-analyse the whole issue, but I assume the `$host` variable is empty in the time of the substitution

I see such messages:
`Use of uninitialized value $host in substitution (s///) at /home/tmolnar/.perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Rex/Logger.pm line 270.`

I use this log format in my Rexfile:
`logformat "[%D] %l %h - %s";`

As a temporary solution I patched my system this way:
(In Rex/Logger.pm)
```
- $line =~ s/\%h/$host/gms;
+ $line =~ s/\%h/$host/gms if $host;
```

**Comment by stiron** [comment]
@krimdomu Do you have any news regarding this one? As I see in several cases the $host cannot be resolved.

**Comment by krimdomu** [comment]
@stiron sorry, i haven't looked into this yet. i think that this happens when there is no connection to any server yet.

**Comment by stiron** [comment]
@krimdomu yeah, that's the case. My quickfix was to use a statement modifier, and do not substitute the $host if it is not present. Alternatively there can be a default <local> in it as in other logs.

If you think I can send a PR with my fix above.

**Comment by ferki** [comment]
@stiron: sounds fine, feel free to send a PR with the `<local>` variation (for consistency).
