### ISSUE TITLE
Firewall.pm module just breaks the whole setup

### ISSUE THREAD

**Issue by fr34k8** [RexOps/Rex#1058]
Bareword "created" not allowed while "strict subs" in use at /loader/0x866c408/Rex/Commands/Firewall.pm line 121.

Bareword "removed" not allowed while "strict subs" in use at /loader/0x866c408/Rex/Commands/Firewall.pm line 121.

**Comment by krimdomu** [comment]
Hi @fr34k8 which version of rex are you using?

**Comment by fr34k8** [comment]
1.4 emerge install

**Comment by krimdomu** [comment]
@fr34k8 since 1.4 the firewall module is included in Rex. So you don't need to use the module from rex-recipes directory. You can just remove `use Rex::Commands::Firewall;` call from your code.
