### ISSUE TITLE
Subtile bug with RE?

### ISSUE THREAD

**Issue by ipcjk** [RexOps/Rex#1078]
I found myself suddenly in a position, where some of my code is not executed or randomly. Tried to short it down and created the attached example task.

My output looks like this:
rex -f Rexfile.JK demo
> I am #Debian# 
> Debian Checkpoint 1 
> Debian Checkpoint 2
> I am #Debian# but did not reach checkpoint 3, even I look like Checkpoint 1
> Debian Checkpoint 4
> I am #Debian# but did not reach checkpoint 5 `

Well I am becoming crazy in my mind today?

**Comment by ipcjk** [comment]
[Rexfile.txt](https://github.com/RexOps/Rex/files/385824/Rexfile.txt)

**Comment by ipcjk** [comment]
Sorry, close this issue. I am blind and just copied / pasted the global matching modifier. too warm today.

**Comment by ferki** [comment]
No problem, and thanks for the feedback. Get some cool drinks ;)
