### ISSUE TITLE
unset sysctl values (follow-up to #1069)

### ISSUE THREAD

**Issue by ferki** [RexOps/Rex#1085]
Since #1069 is merged, it is possible to save values into sysctl config with the `persistent` option, but there's no counterpart of it to remove a specific setting from sysctl config files. I also guess an `ensure => 'present'`/`ensure => 'absent'` style interface would also be more in-line with the rest of the rex interface to control this.

Until then there are two workarounds at least
1. edit the file with file editing commands (like `delete_lines_matching`)
2. update the value in question to its default value with the `persistent` option

**Comment by krimdomu** [comment]
this is already implemented with 826b8bad
