### ISSUE TITLE
Support for SLES 12.2

### ISSUE THREAD

**Issue by LeMerP** [RexOps/Rex#1116]
It is not an issue, but more a small discussion.
As I tried to run a task on a SLES 12.2 machine, I got "OS/Provider not supported". SLES 12.1, however, works like a charm.
Would it not be easier, if the first release of a major version (12) is supported by rex, to support any new minor version (12.x) "automatically"?
I do not think SuSE will put major system changes to a minor upgrade.

**Comment by ferki** [comment]
Thanks for the debugging!

**Comment by krimdomu** [comment]
Hi @LeMerP 
thanks for the report. I've changed the detection to use the regexp.
