### ISSUE TITLE
LVM.pm: stderr of run() should be suppressed

### ISSUE THREAD

**Issue by slashbeast** [RexOps/Rex#1134]
Right now Rex capture stderr and stdout in LVM.pm and tries to parse it, which results in a bogus variables when lvm prints warnings. for example the `my @lines = run 'pvdisplay --units b --columns --separator "|" --noheadings' captures:

    WARNING: Failed to connect to lvmetad. Falling back to device scanning.
    /dev/mapper/enc_root|kagura|lvm2|a--|118954655744B|0B

Which results in setting 

                     'logical_volumes' => [
                                            {
                                              'attributes' => undef,
                                              'path' => '/dev//WARNING: Failed to connect to lvmetad. Falling back to device scanning.',
                                              'size' => undef,
                                              'name' => 'WARNING: Failed to connect to lvmetad. Falling back to device scanning.'
                                            },

**Comment by krimdomu** [comment]
This is a problem with local execution of this line:
https://github.com/RexOps/Rex/blob/development-1.x/lib/Rex/Interface/Exec/Local.pm#L131

I think we should refactor this part to use https://metacpan.org/pod/Capture::Tiny
