### ISSUE TITLE
Perl 5.22+ not supported by JSON::XS

### ISSUE THREAD

**Issue by Alhadis** [RexOps/Rex#1153]
The author of [`JSON::XS`](http://search.cpan.org/~mlehmann/JSON-XS-3.02/XS.pm) has made a [conscious decision](http://blog.schmorp.de/2015-06-06-stableperl-faq.html) to stop supporting modern versions of Perl. Configuring the module currently interrupts a build to prompt manual confirmation from users running Perl 5.22.0 or newer.

Here's an abridged version of [the text being displayed](https://pastebin.com/PvAe04rL):

> ### **[`Canary::Stability`](http://search.cpan.org/~mlehmann/Canary-Stability-2012/Stability.pm) COMPATIBILITY AND SUPPORT CHECK**
>
> In recent releases, P5P (who maintain perl) have been introducing regressions that are sometimes subtle and at other times catastrophic, often for personal preferences with little or no concern for existing code, most notably CPAN. [ … ] Therefore I have introduced a support and compatibility check. This check is just to let you know that there might be a risk, so you can make judgement calls on how to proceed - it will not keep the module from installing or working.  
> …  
> It seems you are running perl version 5.026000, likely the "official" or "standard" version. While there is nothing wrong with doing that, standard perl versions 5.022 and up are not supported by `JSON::XS`. While this might be fatal, it might also be all right - if you run into problems, you might want to downgrade your perl or switch to the "stability branch" †  
>
> † - the author's own version of Perl, forked to *"improve stability and compatibility with existing modules"*.

Going forward, this makes `JSON::XS` as good as abandoned, and imposes compatibility risks with future releases of Perl. Even if such risks are slight, you should consider replacing `JSON:XS` with something more future-proof.

Moreover, [this will impact Rex's continued availability from Homebrew](https://github.com/Homebrew/homebrew-core/pull/14849#pullrequestreview-46120136). The `Canary` warning caused noise while checking formula compatibility with the [newest release of Perl 5.26.0](http://blogs.perl.org/users/sawyer_x/2017/05/perl-5260-is-now-available.html). If a formula isn't stable, it gets pulled from Homebrew's registry. There's no compromise.

**Comment by ehuelsmann** [comment]
Maybe the project should switch to JSON::MaybeXS, which depends on Cpanel::JSON::XS for xs performance

**Comment by krimdomu** [comment]
Many thanks for the info.
This will be fixed in the next release.

**Comment by ilovezfs** [comment]
@Alhadis nice work, but let's try to be nice since he might read this for all we know. ;)
