### ISSUE TITLE
certificate invalid / expired rex.linux-files.org

### ISSUE THREAD

**Issue by fr34k8** [RexOps/Rex#1210]
@krimdomu @ferki  please extend the certificate on the mirrors. its obsolete since February 2018

**Comment by AaronJackson** [comment]
I'm a big fan of Rex, but I'm pretty disappointed that stuff line SSL certificates aren't even getting updated. :(

**Comment by fr34k8** [comment]
@krimdomu @ferki dudes ! tschaaakaa! this is anoying.. fix it please asap

**Comment by krimdomu** [comment]
Hi all,
sorry for the delay. I'm working on it now.

**Comment by AaronJackson** [comment]
Thank you @krimdomu :grinning:

**Comment by krimdomu** [comment]
So, i migrated it to Amazon Cloud Front, so the ssl cert updates automatically. The clients need to support SNI but i think all clients today do support it.

It might take a while until the DNS updates.

**Comment by AaronJackson** [comment]
:+1:  Thanks again
