### ISSUE TITLE
Run CI infrastructure for each PR and merge commit

### ISSUE THREAD

**Issue by ehuelsmann** [RexOps/Rex#1218]
Steps towards a satisfactory test suite scope:

1. [x] Run test suite through `prove`
2. [x] Run test suite on TravisCI (or other CI)
2. [ ] Add [Test::MinimumVersion](https://metacpan.org/pod/Test::MinimumVersion)
3. [ ] Test at least current and minimum Perl versions ("test matrix" in "TravisCI-speak")
4. [ ] Perl critic test for code being tidy

**Comment by ehuelsmann** [comment]
For reference: a lot of experience regarding the above is encapsulated in: https://github.com/RexOps/Rex/pull/1005/commits/b6dab5ed4f5c96db00de76b3b96c56bfae6954bb

**Comment by ferki** [comment]
I think we could consider this issue as solved:

- Add Test::MinimumVersion
    It's in `dist.ini` and is being run as an author test. Configuration was updated on c4e35d62ed416e2a5f58713bcef9c10ef544e72b to match current goals.

- Test at least current and minimum Perl versions ("test matrix" in "TravisCI-speak")
    There are 3 parallel jobs offered by Travis CI as part of the free usage, and that is now used to test latest perl version on 3 platforms (Linux, Windows, Mac OS X). Older Perl versions gets tested by CPAN Testers.

    I consider this a good compromise between CI feedback speed and perl version coverage, but of course we can try to find a better balancing point.

- Perl critic test for code being tidy
    There's an author test for tidiness since 8fecbf6e041e0fd4df03b4d6d94958a6ebc257f7. Perl::Critic is used during CI runs to quickly check tidiness of the bin files, which can't be (at least easily) included in the filelist for Test::Perltidy.

@ehuelsmann: what do you think? Are there anything more to work on the CI side in the scope of this issue?

**Comment by ferki** [comment]
As mentioned above, I consider this as solved, therefore I'm closing the issue.

Of course, feel free to reopen it, or to open new issue(s) about testing and/or CI integration.
