### ISSUE TITLE
before_task_start broken in Rex 1.8.1

### ISSUE THREAD

**Issue by tomhukins** [RexOps/Rex#1271]
I've started working with a Rex installation that runs fine with Rex 1.6.0 but encounters problems with Rex 1.8.1.  I've been able to reduce the installation to a simple Rexfile that demonstrates the problem:

```
use Rex -feature => ['1.4'];
use Rex::Commands::User;

task base => sub {
    say "BASE";
};

before_task_start base => sub {
    say "BEFORE";
};
```

With Rex 1.6.0 I see the following:
```
% rex base                                   
BEFORE
[2020-02-24 16:23:44] INFO - Running task base on <local>
BASE
[2020-02-24 16:23:44] INFO - All tasks successful on all hosts
```

And with Rex 1.8.1 I see the following:
```
% rex base
[2020-02-24 16:40:25] INFO - Can't add before_task_start base, as it is not yet defined
see /loader/0x8016fea38/__Rexfile__.pm line 10
[2020-02-24 16:40:25] INFO - Running task base on <local>
BASE
[2020-02-24 16:40:25] INFO - All tasks successful on all hosts
```

With 1.8.1, the before code doesn't run.  I wonder if this is related to #1193, but I don't know enough about Rex yet to be sure.

**Comment by ferki** [comment]
Thanks for the report with the instructions to reproduce!

Interestingly enough, the test suite somehow misses this case, despite exercising all types of hooks. It's definitely a case that should be part of the tests.

And yes, it sounds possible that this is related to some combination of hooks and namespaces.

**Comment by ferki** [comment]
@tomhukins: this should be fixed in the master branch already, and would be included in the next release. Thanks again for the report!
