### ISSUE TITLE
account() fails with 'comment' including non-ASCII character when `use utf8;` is in effect

### ISSUE THREAD

**Issue by dboehmer** [RexOps/Rex#1274]
My last name *Böhmer* contains a German umlaut *ö*. Setting the `comment` of my user account via SSH fails.

Example:

```perl
#!/usr/bin/env perl

use strict;
use warnings;

use utf8;
use Rex;

user 'root';

task test => sub {
    account 'daniel' => (
        comment     => "Daniel Böhmer",
        create_home => FALSE,
    );
};
```

Ran it like:

    $ rex -d -H $HOST test

**Comment by ferki** [comment]
@dboehmer: could you also attach your immediate error message to the opening post as well, please? The one that complains about the JSON (de)serialization.

My initial triaging suggests that the behavior might be slightly different depending on which JSON module is loaded by `JSON::MaybeXS`, but I still couldn't reproduce your case.

Following that lead, please also post which version of which JSON module gets loaded on the system where you are running rex. If all's well, then I would be able to reproduce the same results based on that info.

**Comment by dboehmer** [comment]
I hope you had a pleasant journey back home:-)

Seems like the error persists although the relevant modules are up to date:

```
$ rex -H $HOST test
[2020-03-10 17:21:11] INFO - Running task test on XXX_HOST_XXX
[2020-03-10 17:21:13] ERROR - Error executing task:
[2020-03-10 17:21:13] ERROR - malformed UTF-8 character in JSON string, at character offset 136 (before "\x{fffd}r","/home/da...") at /home/daniel/perl5/perlbrew/perls/perl-5.30.0-threads-buster/lib/site_perl/5.30.0/Rex/User/Linux.pm line 353, <> line 45.

[2020-03-10 17:21:13] ERROR - 1 out of 1 task(s) failed:
[2020-03-10 17:21:13] ERROR -   test failed on XXX_HOST_XXX
[2020-03-10 17:21:13] ERROR -           malformed UTF-8 character in JSON string, at character offset 136 (before "\x{fffd}r","/home/da...") at /home/daniel/perl5/perlbrew/perls/perl-5.30.0-threads-buster/lib/site_perl/5.30.0/Rex/User/Linux.pm line 353, <> line 45.
$ 
$ cpanm JSON JSON::XS JSON::MaybeXS Rex
JSON is up to date. (4.02)
JSON::XS is up to date. (4.02)
JSON::MaybeXS is up to date. (1.004000)
Rex is up to date. (1.8.2)
```

**Comment by ferki** [comment]
Thanks for the extra input, I could now reproduce it, and turned out I won't need the JSON details. The key was to have `use utf8;` in the Rexfile.

**Findings so far**

Rex currently uses an temporary file on the remote for user management actions on managed Linux machines. Then this file gets executed to carry out the given action.

The problem seems to be that this file seems to be `ISO-8859` encoded instead of `UTF-8` (according to the `file` CLI utility). Which is a bit even more weird, since the built-in `file` command uses the same file handling interfaces internally, and that does not seems to be affected.

**Workaround**

Here's a patch as a workaround for this given issue:
```diff
diff --git a/lib/Rex/User/Linux.pm b/lib/Rex/User/Linux.pm
index edbc63a6..1c99e0fe 100644
--- a/lib/Rex/User/Linux.pm
+++ b/lib/Rex/User/Linux.pm
@@ -164,13 +164,7 @@ sub create_user {
 
   # only run the cmd if needed
   if ($run_cmd) {
-    my $rnd_file = get_tmp_file;
-    my $fh       = Rex::Interface::File->create;
-    $fh->open( ">", $rnd_file );
-    $fh->write("rm \$0\n$cmd $user\nexit \$?\n");
-    $fh->close;
-
-    i_run "/bin/sh $rnd_file", fail_ok => 1;
+    i_run "$cmd $user", fail_ok => 1;
     if ( $? == 0 ) {
       Rex::Logger::debug("User $user created/updated.");
     }
```

**TODO**

I'll debug it further to understand the differences in the resulting file encodings, and I expect that would lead us to a more complete solution.

**Comment by ferki** [comment]
So it seems like the write methods in `Rex::Interface::File::*` modules get confused on what encoding to use on the remote machines for file write operations when `use utf8;` is in effect.

I'm tempted to simply force UTF-8 encoding there, but perhaps it's better if that behavior is configurable. Both for what the default encoding should be (utf-8? autodetect? based on what?), and to be able to choose your own preference.

**Comment by dboehmer** [comment]
> Thanks for the extra input, I could now reproduce it, and turned out I won't need the JSON details. The key was to have `use utf8;` in the Rexfile.

It was included in the original issue for a reason :wink:

> ferki changed the title <s>account() fails with 'comment' including non-ASCII character</s> account() fails with 'comment' including non-ASCII character when `use utf8;` is in effect

Sorry to say but I think you changed the title to be *less* correct than before.

“`use utf8` in effect” only means that the input file enabling this pragma is known to be encoded in UTF-8. Nothing else.

Maybe try:

```perl
#!/usr/bin/env perl

use strict;
use warnings;

### no 'use utf8;'
use Rex;

user 'root';

task test => sub {
    account 'daniel' => (
        comment     => "Daniel B\N{LATIN SMALL LETTER O WITH DIAERESIS}hmer",
        create_home => FALSE,
    );
};
```

In either case Perl now holds a string with a Unicode char that was correctly decoded from the input file. I think the challenge then is to correctly encode it to the output file and correctly flag its encoding. I’d suggest a solution but I have no overview over Rex’s file abstraction yet.

**Comment by dboehmer** [comment]
> I'm tempted to simply force UTF-8 encoding there, but perhaps it's better if that behavior is configurable. Both for what the default encoding should be (utf-8? autodetect? based on what?), and to be able to choose your own preference.

It’s the duty of the Rex user to correctly flag the encoding of their `Rexfile` file. I think you may then create an output file for the target system with any encoding you want. Writing UTF-8 will be a reasonable choice. I don’t know yet what the output file actually is but if it is Perl again, simply include `use utf8`.

**Comment by ferki** [comment]
We've decided to add a new feature flag called `write_utf8_files` to control the encoding of files written by Rex. This is intended to complement `use utf8;` pragma in Rexfiles.

```
use Rex -feature => ['write_utf8_files'];
```

In all the various use-cases to reproduce this issue and related behaviour, enabling that feature solved them.

It's already merged to master branch if you'd like to give it an early spin, but there also should be a dev release including it as well. Looking forward to your results and feedback.
