### ISSUE TITLE
WARN - An error occured for update_system: Error updating system at /home/bitnami/perl5/lib/perl5/Rex/Pkg/Base.pm line 110.

### ISSUE THREAD

**Issue by sdondley** [RexOps/Rex#1288]
I set up a virtual server using Amazon Lightsail. As best I can tell, it's an ubuntu machine. `uname -a` yields something like:

`Linux ip-172-123-3-2 4.4.0-1104-aws RexOps/rexify-website#115-Ubuntu SMP Mon Mar 2 06:35:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

The `update_system` rex command chokes with:

 `WARN - An error occured for update_system: Error updating system at /home/bitnami/perl5/lib/perl5/Rex/Pkg/Base.pm line 110.`

How do I go about fixing this?

**Comment by ferki** [comment]
At this point it looks more like a support question and for that our [IRC channel](https://kiwiirc.com/nextclient/#irc://irc.freenode.net/#rex?nick=mc-guest-?) or [Rex Users group](https://groups.google.com/forum/#!topic/rex-users) are generally considered as much better suited communication platforms.

> I set up a virtual server using Amazon Lightsail. As best I can tell, it's an ubuntu machine. `uname -a` yields something like:
> 
> `Linux ip-172-123-3-2 4.4.0-1104-aws RexOps/rexify-website#115-Ubuntu SMP Mon Mar 2 06:35:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

I don't have direct experience with Lightsail yet, and this `uname` info seems to have some kind of copy-paste error (it contains `RexOps/rexify-website#115`), but I agree it looks like Ubuntu.

> `WARN - An error occured for update_system: Error updating system at /home/bitnami/perl5/lib/perl5/Rex/Pkg/Base.pm line 110.`
> 
> How do I go about fixing this?

Please run your task with `rex -d` to obtain the debug output, and see which command fails exactly. My guess would be `APT_LISTCHANGES_FRONTEND=none DEBIAN_FRONTEND=noninteractive apt-get -y -qq upgrade` for the failing command (at least that's what Rex is trying to execute on Ubuntu when calling `update_system`). If that doesn't work, it might be an issue specific to Lightsail systems. If the command is different than that, then we probably need to teach Rex to recognize these systems properly.

If you need further help with it, make sure it doesn't contain sensitive information, and upload it to a paste service like [pastebin.com](https://pastebin.com) or even [gist.github.com](https://gist.github.com). Then link it here for further inspection.

**Comment by sdondley** [comment]
Sorry, for the confusion.

`uname -a` yields:`

`Linux ip-111-222-7-123 4.4.0-1104-aws #115-Ubuntu SMP Mon Mar 2 06:35:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Here is the debug output: 
[debug.log](https://github.com/RexOps/Rex/files/4457660/debug.log)

**Comment by sdondley** [comment]
OK, took a close look at file. Found this:

```
1179 [2020-04-09 17:10:10] DEBUG - SSH/executing: LC_ALL=C ; export LC_ALL; PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/pkg/bin:/usr/pkg/sbin; export PATH; APT_LISTCHANGES_FRO     NTEND=none DEBIAN_FRONTEND=noninteractive apt-get -y -qq upgrade
1180 [2020-04-09 17:10:10] DEBUG - ========= ERR ============
1181 [2020-04-09 17:10:10] DEBUG - E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
1182 E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
1183
1184 [2020-04-09 17:10:10] DEBUG - ========= ERR ============
1185 [2020-04-09 17:10:10] DEBUG -
1186 ^[[0m^[[33m[2020-04-09 17:10:10] WARN - An error occured for update_system: Error updating system at /home/bitnami/perl5/lib/perl5/Rex/Pkg/Base.pm line 110.
```

Looks like some kind of permission problem and has to be run as sudo, I'm guessing. Which makes sense.

**Comment by sdondley** [comment]
Issue was the command has to be run as sudo. Following the guide on the website, doing this worked:

ask 'update_system', sub {
  sudo {
    command => sub {
      update_system;
    },
    user => 'root'
  };
};

**Comment by ferki** [comment]
Thanks for the followup here! So it was a permission problem after all.

Using sudo with Rex may take many forms. I'd recommend taking a look at the [sudo documentation](https://metacpan.org/pod/Rex::Commands::Run#sudo) as well, perhaps you find a format that better fits your use case.

ps.: I believe the other error messages mentioning `Permission denied` might be related too (e.g. when Rex executes `dmidecode` while it tries to discover what type of machine it is asked to manage).

```
[...]
[2020-04-09 17:10:09] DEBUG - Executing: export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/pkg/bin:/usr/pkg/sbin ; LC_ALL=C which dmidecode
[2020-04-09 17:10:09] DEBUG - /usr/sbin/dmidecode

[2020-04-09 17:10:09] DEBUG - Executing: export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/pkg/bin:/usr/pkg/sbin ; LC_ALL=C dmidecode
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: Permission denied
[...]
```
