### ISSUE TITLE
Trying to connect to host during tests

### ISSUE THREAD

**Issue by ferki** [RexOps/Rex#1306]
@thrig reported via IRC:

```
--> Working on Rex
Fetching http://www.cpan.org/authors/id/F/FE/FERKI/Rex-1.9.0.tar.gz ... OK
Configuring Rex-1.9.0 ... OK
The authenticity of host 'asdfsadfasdf (96.126.123.244)' can't be established.
ECDSA key fingerprint is SHA256:cKAqkTAmobyA+VUC+KrG6uVHgJ+z+EG3USYCjqBQJCw.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
```

Looks like some of the tasks defined in the test suite had the weird default hostname of `asdfsadfasdf`, making rex try to connect to it. This is clearly a bug, the test suite is not supposed to use the network.

**Comment by thrig** [comment]
also some (naughty?) ISP like to create wildcard DNS records, which is probably where this came from

**Comment by ferki** [comment]
It's a good catch, thanks for reporting! :+1:
