### ISSUE TITLE
Document how to use existing ssh master connection

### ISSUE THREAD

**Issue by sdondley** [RexOps/Rex#1309]
Currently, there is no documentation, that I could find, for using an existing ssh connection through a socket:

```
my %hash = (initialize_options => {'external_master' => 1, 'ctl_path' => '/home/me/.ssh/socket_name'});
Rex::Config->set_openssh_opt(%hash);

**Comment by ferki** [comment]
If I understand correctly, as far as Rex documentation is concerned, the real scope here is "how to set Net::OpenSSH object constructor options". That is, the related user story format would probably look something like:

>**As:** a rex user,
**I would like to:** know how to set constructor options for the underlying Net::OpenSSH object,
**so:** I could fine-tune connection details according to my use case.

This topic possibly could go directly into `Rex::Interface::Connection::OpenSSH`, and it would probably help to change the issue title accordingly.

For the list of available options, probably the best we could do is to point readers to the corresponding external documentation: [Net::OpenSSH->new()](https://metacpan.org/pod/Net::OpenSSH#Net::OpenSSH->new($host,-%opts)).

That being said, setting a master connection can definitely be (one of) the code example(s).

**Comment by ferki** [comment]
Closing as duplicate in favor of #1311. If any code examples are wished to be included, the one about external master could still be the one (or one of them.).
