### ISSUE TITLE
Rex chokes when "external_master" openssh option is set

### ISSUE THREAD

**Issue by sdondley** [RexOps/Rex#1310]
See https://github.com/RexOps/Rex/issues/1309 for reference. external_master option is explained here: https://metacpan.org/pod/Net::OpenSSH#external_master

Fix needed at `Rex/Interface/Connection/OpenSSH.pm` at line 97 to:

```
  push @connection_props, master_opts      => \@ssh_opts_line if @ssh_opts_line
    && !($net_openssh_constructor_options{external_master});
```

Proper test and patch forthcoming.

**Comment by ferki** [comment]
Good catch, and without looking at the code context, the proposed patch seems about right :+1:
