### ISSUE TITLE
improve documentation regarding "auth for" operation wrt groups

### ISSUE THREAD

**Issue by sdondley** [RexOps/Rex#1314]
Documentation should make it explicit that "auth for" command works only for named groups and not for individuals hosts in the group. In other words, if a task is issued to a host from the command line with the -H option, the credentials that apply for the group will not be applied to the individual server even if it is part of a group with an "auth for" command applied to it.

**Comment by sdondley** [comment]
It may be desirable to change Rex's behavior so that Rex will apply apply credentials for a group to an individual host. However, this can get complicated because a host can belong to more than one group. In such a case, there would be a conflict.

**Comment by ferki** [comment]
> Documentation should make it explicit that "auth for" command works only for named groups and not for individuals hosts in the group.

Currently it says:

"With this function you can modify/set special authentication parameters for tasks and groups."

It already correctly doesn't mention any hosts :confused:

> In other words, if a task is issued to a host from the command line with the -H option, the credentials that apply for the group will not be applied to the individual server even if it is part of a group with an "auth for" command applied to it.

Correct, the `-H` CLI option is an override compared to what is described in Rexfile. If the task has a default group to run against (the "locality" of the task), then `-H` overrides that (replaces the group locality with the host locality).

Perhaps, the CLI options need more docs instead?

> It may be desirable to change Rex's behavior so that Rex will apply apply credentials for a group to an individual host.

The [`group`](https://metacpan.org/pod/Rex::Commands#group($name,-@servers)) command (and the [`use_server_auth`](https://www.rexify.org/docs/release_notes/0.42.html#newfeatureflaguse_server_authtoenableauthpropertiesininifiles) feature flag for group files) is supposed to handle host-specific auth info to some extent.

For implementing more complex authentication use cases either on-the-fly code generation, or offloading as much as possible to ssh agent/config is recommended.

> However, this can get complicated because a host can belong to more than one group. In such a case, there would be a conflict.

Yup, with declaration possibilities at multiple levels, the complexity of "get this done right for everyone" is increasing rapidly too. It's OK to provide some building blocks for the common use cases in Rex core. But if we're going to change things around auth, I'd really go more in the direction of "let's offload it to something else that already does that" for more complex use cases (e.g. use ssh config to describe where to use what credentials and options to log in).

Right now, I'm not convinced that the current docs need to be modified for `auth for`, but I'm keeping this open for a bit more in case there's a PR coming with an actual proposal, or more ideas emerge.

**Comment by sdondley** [comment]
Omission of a fact does not make the fact explicit. If one might reasonably assume the software *could* work that way and that it's just missing from the documentation, I think it's a good idea to spell out that it doesn't work this way.

**Comment by ferki** [comment]
After getting a sleep, I feel like this issue got inflated to contain much more than the immediate issue, and a lot of signal has lost in the noise as a result.

To keep a better balance of "what it does" vs "what it doesn't do", I'll prepare a PR to include a note about command line option precedence, and pointing to the `group` command for per-host authentication.
