### ISSUE TITLE
"needs" function does not work as documented with the "main" package

### ISSUE THREAD

**Issue by sdondley** [RexOps/Rex#1326]
## Describe the bug

The function at https://metacpan.org/pod/Rex::Commands#needs does not appear to work as documented. When `main` is the argument to the function, the task is called immediately which I don't think it what is intended.

## How to reproduce it

Use the code as documented with a `main` argument:

`needs main "uname";`
## Expected behavior

Nothing should happen with this line of code. The `uname` task should not be executed.

## Circumstances

 - Rex version: 1.10
 - Perl version: 5.24
 - OS running rex: mac

## To fix the behavior:

```
needs Rex::CLI "uname";

# Now the task can be called as usual:
run_task('uname');
```

**Comment by ferki** [comment]
> When main is the argument to the function, the task is called immediately which I don't think it what is intended.

This is intended. That's the exact purpose of `needs` command is to run the named task immediately (minus any of its attached hooks), with one of the following forms:

  - `needs "$taskname"`: execute `$taskname` from the same namespace where called
  - `needs $namespace`: execute all tasks defined in `$namespace` in the order they are defined
  - `needs $namespace "$taskname"`: execute `$taskname` as specified in `$namespace`

There are test for this behaviour in `t/needs.t`.

For the tasks directly specified in the Rexfile, the special `main` namespace is recognized as documented:

  - `needs main "$taskname"`: execute `$taskname` as specified in the Rexfile

So perhaps what is borderline bug/new feature in the `needs` context is to let Rex recognize `Rex::CLI` as the same as the `main` namespace to be more consistent with fully qualified task naming used elsewhere. But that's a different issue.

**Comment by sdondley** [comment]
If that's the way it is intended, to execute immediately, then there doesn't seem to be a way to pass in arguments to the receiving task. If there is, this does not appear to be documented.

**Comment by ferki** [comment]
There's no way to arguments with `needs`. If you need to pass arguments, use [`run_task`](https://metacpan.org/pod/Rex::Commands#run_task).

**Comment by sdondley** [comment]
Hmm, when I did just a plain `run_task` it did not work for a task in the Rexfile. That led met to believe it wasn't possible so I tried the `needs` function.

But oddly, everything is working now with just a plain `run_task`. I probably had a typo before. Sorry to bother.
