### ISSUE TITLE
malformed JSON string error when running rexify --use Rex::Misc::ShellBlock

### ISSUE THREAD

**Issue by sdondley** [RexOps/Rex#1332]
## Describe the bug

Following error message appears when running `rexify --use Rex::Misc::ShellBlock`

`malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at /Users/me/perl5/perlbrew/perls/perl-5.24.1/bin/rexify line 361.`
## Environment

 - Rex version: 1.10
 - Perl version: 5.24.4
 - OS running rex: macos, 10.15.4

**Comment by sdondley** [comment]
Possibly related: https://github.com/RexOps/Rex/issues/1201

It's hard to say how this is all supposed to work as the `rexify` command appears to be completely undocumented except for references to using it that can be found on rexify.org.

**Comment by ferki** [comment]
This is exactly #1201. Closing as duplicate.
