### ISSUE TITLE
Create tests for Rex::Commands::Rsync

### ISSUE THREAD

**Issue by sdondley** [RexOps/Rex#1354]
They Rsync command is generally functional but contains some limitations and bugs that need to be addressed. Unfortunately, no tests for the module are present in the current Rex distribution. Basic tests should be created for the module as it currently exists and then for any existing patches and any future ones.

Current issues are:

#1356
#1355
#1315
#1290
#1075

Existing patches:

#1353
#1298

I'm willing to write tests for the issues and patches above if someone can get the ball rolling by writing basic tests for the Rsync module as it exists today.

**Comment by ferki** [comment]
I wonder if there's any problems with the pre-defined issue and PR templates. Are they not showing up when opening a new issue/PR?

**Comment by sdondley** [comment]
Sorry, I don't like templates for issues and take them as suggestions only.

**Comment by sdondley** [comment]
I will take a look at sync_test branch when I get a chance and let you know if I have any questions.

**Comment by ferki** [comment]
> Sorry, I don't like templates for issues and take them as suggestions only.

They exist for a reason, please don't ignore them. They help to formulate the actual intent of any new issue and PR, and streamlines work with them by taking out a good chunk of the guesswork.

> I will take a look at sync_test branch when I get a chance and let you know if I have any questions.

I'll clean them up soon-ish to have an initial local test for a generic case, and then add a test/fix pair of commits for #1075 separately.
