### ISSUE TITLE
Rex::Commands::Rsync is setting -r and -l switches automatically

### ISSUE THREAD

**Issue by sdondley** [RexOps/Rex#1355]
See https://github.com/RexOps/Rex/blob/master/lib/Rex/Commands/Rsync.pm#L151

The -r and -l switches are set for the rsync command. I'm not sure if there is a good reason for this but if there is, this should at least be documented.

**Comment by ferki** [comment]
Hmm, for some reason this also doesn't follow the issue templates.

In the linked code I see `-r` and `-l` - is it just a typo in the title/OP?

**Comment by sdondley** [comment]
Fixed wetware memory error.
