### ISSUE TITLE
cmdb documenation does not match behavior ($server argument is ignored)

### ISSUE THREAD

**Issue by sdondley** [RexOps/Rex#1374]
## Describe the bug

See the documentation for retrieving a value from the cmdb database: https://metacpan.org/pod/Rex::CMDB#cmdb

With cmdb defaults and according to the documentation, I expect the following code to return the value associated with 'some_key' located in cmdb/some_server.yml (or cmdb/environment/some_server.yml or cmdb/my_os/some_server.yml):

`my $value = get cmdb('some_key', 'some_server');`

This is not the case, however. When the above code is execute in a task, the server argument is ignored and Rex tries to pull the key from the yml file for the server the task is being run on. When the above code is executed outside of task, the value is pulled from the local host's cmdb file

## How to reproduce it

1. create a cmdb/some_server.yml and add key/value pairs to it
2. attempt to retrieve values from yml file with `get cmdb` when not running a task on `some_server`

Shortest code example that demonstrates the bug:

In file cmdb/some_server.yml, add this key/value pair:

`some_key: some_value`

```perl
use strict;
use warnings;
use Rex -feature => [ qw( 1.4 ) ];

task test, 'some_other_server', sub {
  my $value = get cmdb('some_key', 'some_server'));
  print $value;
};

```

## Expected behavior

`$value` should be value found in `some_server.yml` file. Instead, value from `some_other_server.yml` (if it exists) is returned.

## Circumstances

 - Rex version: 1.11
 - Perl version: 5.24.4
 - OS running rex: Darwin
 - OS managed by rex: Darwin

*Additional notes:*
The bug seems to be introduced at https://github.com/RexOps/Rex/blob/master/lib/Rex/CMDB/YAML.pm#L96

This line eventually calls the `parse_path` function: https://github.com/RexOps/Rex/blob/master/lib/Rex/Helper/Path.pm#L216

This function only uses the current connection to determine the server. So any $server argument passed to `get cmdb()` just gets ignored.

**Comment by ferki** [comment]
It sounds like an interesting bug, thanks for the report!

There's already tests for server-based lookups in `t/cmdb.t`, but maybe not for the "look up other server's data" scenario. Off the top of my head, it can be that the recently added CMDB caching interferes with the previous behavior.

Perhaps it would be best to first demonstrate the failure by adding test cases in the above file, and then figuring out what would be the best strategy to fix it.
