### ISSUE TITLE
Test Failure task.t 1.12.0

### ISSUE THREAD

**Issue by perlpunk** [RexOps/Rex#1377]
## Describe the bug

The test task.t fails in SUSE Open Build Service

https://build.opensuse.org/package/live_build_log/devel:languages:perl:autoupdate/perl-Rex/standard/x86_64

```
[   57s] 
[   57s] #   Failed test 'get connection type for ssh'
[   57s] #   at t/task.t line 52.
[   57s] #          got: 'SSH'
[   57s] #     expected: 'OpenSSH'
[   57s] 
[   57s] #   Failed test 'get connection type for ssh'
[   57s] #   at t/task.t line 63.
[   57s] #          got: 'SSH'
[   57s] #     expected: 'OpenSSH'
[   57s] # Looks like you failed 2 tests of 36.
[   57s] t/task.t ........................... 
[   57s] Dubious, test returned 2 (wstat 512, 0x200)
[   57s] Failed 2/36 subtests 
[   57s] t/task_hosts.t ..................... ok

```

## Circumstances

 - Rex version: 1.12.0
 - Perl version: 5.30.1
 - OS running rex: OpenSUSE Leap 15.1

**Comment by perlpunk** [comment]
I think it might be because of this line:
https://metacpan.org/source/FERKI/Rex-1.12.0/Makefile.PL#L193
Our script to autogenerate the rpm spec file might be missing this, so I have to add the dependency manually.

**Comment by perlpunk** [comment]
Ok, I think the problem is on our side. On one machine, the dependencies are correctly identified, on the other one not.

**Comment by ferki** [comment]
Hmm, that's interesting. I'm glad it's solved, and thanks for the report anyway, @perlpunk!

I expect some work to be done around optional and OS-specific dependencies in the future, so feel free to let us know if you are experiencing these kind of issues.
