### ISSUE TITLE
Possibly leftover file rsync.t2?

### ISSUE THREAD

**Issue by perlpunk** [RexOps/Rex#1378]
The archive for 1.12.0 contains a new file `rsync.t2` in the root directory. I cannot see it used anywhere, so maybe this was added accidentally?

**Comment by ferki** [comment]
Ooops, yes, I don't think that should be in there, thanks! I'll remove that file, and will look for a dzil way to prevent these kind of issues in the future.

**Comment by ferki** [comment]
Note to self: I use [Dist::Zilla::Plugin::MatchManifest](https://metacpan.org/pod/Dist::Zilla::Plugin::MatchManifest) elsewhere, check if it's a good idea for Rex too.
