### ISSUE TITLE
Allow provide a string with yaml in it to fill group_yaml

### ISSUE THREAD

**Issue by gonzalo-radio** [RexOps/Rex#1381]
## User story

**As** a contributor 
**I would like to** define my groups_yaml from a string instead of a file  
**so I can** avoid the requirement of write it to a file .

## Describe the solution you'd like

I already have a solution implemented and the pull request is coming next to this issue.

My proposal uses [YAML::load](https://metacpan.org/pod/distribution/YAML/lib/YAML.pod#Load(string-containing-a-YAML-stream)) to read the string with the yaml inside.
Is optional and you have to use `groups_yaml` passing `load_string` with `TRUE` value to active it.

## Describe alternatives you've considered

i don't have one, but i am open to other solutions :)

## Additional context

Maybe this is possible to do in another way, if this is true, please, let me know.

Sorry for mi English, i am working on it.

**Comment by ferki** [comment]
If all the data about hosts and hostgroups are available in a variable, I would recommend to iterate over them in a loop and call the built-in [`group`](https://metacpan.org/pod/Rex::Commands#group) command for each hostgroup with its members. That's basically what `groups_yaml` does under the hood as well. Something like:

```perl
for my $hostgroup ( keys %{%servers_yaml} ) {
    my @servers = @{$servers_yaml{$hostgroup}};
    group $hostgroup => @servers;
};
```

@gonzalo-radio: would that work for you too?

**Comment by gonzalo-radio** [comment]
oh! yes, i think it should work. 

This way i also can add additional parameters to the servers, right? 

Let me try and let you know about the result, thank you!

**Comment by ferki** [comment]
> This way i also can add additional parameters to the servers, right?

I'm not sure without actually looking into it. You might need to call

```
my $server = Rex::Group::Entry::Server->new( name => $servername, %parameters );
```

or something similar for each server to achieve that.

> Let me try and let you know about the result, thank you!

Sure, let me know how that goes!

**Comment by gonzalo-radio** [comment]
> > This way i also can add additional parameters to the servers, right?
> 
> I'm not sure without actually looking into it. You might need to call
> 
> ```
> my $server = Rex::Group::Entry::Server->new( name => $servername, %parameters );
> ```
> 
> or something similar for each server to achieve that.
> 
> > Let me try and let you know about the result, thank you!
> 
> Sure, let me know how that goes!

By default the group function returns a `Rex::Group::Entry::Server` and accepts a `HashRef` so it works like this:

```perl
#!/usr/bin/env perl

use Rex -base;
use Rex::Group;
use Mojo::UserAgent;
use Mojo::Collection qw/ c /;
use Data::Dump qw/ pp /;

my $ua        = Mojo::UserAgent->new;
my $inventory = $ua->get('http://somedomain.com/cmdb/ansible')->res->json;

for my $group (grep { $_ !~ /_meta|all/ } keys $inventory->%*) { 
    my $hosts = c($inventory->{$group}{hosts}->@*)->map(sub{
        ( $_, $inventory->{_meta}{hostvars}{$_} ) 
    });
    group( $group => $hosts->@* );
}

no_ssh task 'test', sub {
    c(Rex::Group->get_group('somegroup'))->each(sub{
        say ref( $_ ); # Rex::Group::Entry::Server
        say pp ($_->{somekey});
    }); 
};
```

I can go with this option to load my groups.

**Comment by ferki** [comment]
> I can go with this option to load my groups.

Sounds great, and I think that's a quite nice example there, thanks!

It sounds like we can close this issue and the related PR then. Feel free to reopen or open new ones if needed!
