### ISSUE TITLE
Using custom server properties with INI files are undocumented

### ISSUE THREAD

**Issue by djzort** [RexOps/Rex#1405]
NOTE: original post edited for clarity

## Describe the bug

Rex supports describing custom server properties in an INI file, but it does not seem to be documented outside the [original release note for 0.42](https://www.rexify.org/docs/release_notes/0.42.html#defineservergroupswithspecialserverpropertiesininifiles).

## How to reproduce it

~~Steps to reproduce the behavior:~~

~~Shortest code example that demonstrates the bug:~~

## Expected behavior

This capability of Rex::Group::Lookup::INI should be documented in the module's POD.

## Circumstances

 - Rex version: 1.12.1
 - Perl version: any
 - OS running rex: any
 - OS managed by rex: any
 - ~~How rex was installed: ~~

## Original report

The Rex::Group::Lookup::INI module allows hostgroups to be provided in an ini file

It would be very useful if per-host variables could be provided similar to Ansible https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#adding-variables-to-inventory

**Comment by ferki** [comment]
Oh, I'm afraid [my comment](https://github.com/RexOps/rexify-website/issues/156#issuecomment-678737432) on RexOps/rexify-website#156 might have been misunderstood.

> [...] this feature itself is available since version 0.42 (~2013). Unfortunately it seems it was only mentioned in the [release notes](https://www.rexify.org/docs/release_notes/0.42.html#defineservergroupswithspecialserverpropertiesininifiles), and hasn't been documented properly in [Rex::Group::Lookup::INI](https://metacpan.org/pod/Rex::Group::Lookup::INI) yet.

> Could you open a bug report about the missing documentation [...] instead of this one, please?

I find opening it as a feature request and ignoring the issue template both misleading and confusing. Let me try to fix this by editing the issue title and the opening post as a bug report.

**Comment by djzort** [comment]
Awesome thanks
