### ISSUE TITLE
apt-get remove action requires DEBIAN_FRONTEND=noninteractive set for unattended remove

### ISSUE THREAD

**Issue by mestia** [RexOps/Rex#1411]
## Describe the bug

Debconf prompt on a package removal causes rex to stuck.

## How to reproduce it

1. install libnss-ldapd:
apt-get install libnss-ldapd

2. try to remove it with rex:

task "remove_ldap_client", sub {
    pkg 'libnss-ldap', ensure => "absent";
};

3. rex -H testhost remove_ldap_client

Shortest code example that demonstrates the bug:

See above.
## Expected behavior

rex suppose to remove the package

## Circumstances

 - Rex version: 1.12.1
 - Perl version: 5.30.3
 - OS running rex: Debian buster
 - OS managed by rex: Ubuntu 20.04
 - How rex was installed: Debian package

## Possible solution
```
--- a/lib/Rex/Pkg/Debian.pm
+++ b/lib/Rex/Pkg/Debian.pm
@@ -34,7 +34,7 @@ sub new {
       'APT_LISTCHANGES_FRONTEND=none DEBIAN_FRONTEND=noninteractive apt-get -y -qq upgrade',
     dist_update_system =>
       'APT_LISTCHANGES_FRONTEND=none DEBIAN_FRONTEND=noninteractive apt-get -y -qq dist-upgrade',
-    remove            => 'apt-get -y remove %s',
+    remove            => 'APT_LISTCHANGES_FRONTEND=none DEBIAN_FRONTEND=noninteractive apt-get -y remove %s',
     purge             => 'dpkg --purge %s',
     update_package_db => 'apt-get -y update',
   };
```

**Comment by ferki** [comment]
@mestia: thanks for the report! Do you think any other `apt-get` commands would need these environment variables too?

I'm thinking about making that default in the module for all the command calls. Do you think that's a good idea? Would it work with `dpkg` as well (I guess it won't interfere)?

**Comment by mestia** [comment]
`dpkg` is affected too, is it possible to export `APT_LISTCHANGES_FRONTEND=none DEBIAN_FRONTEND=noninteractive` and ` APT_LISTBUGS_FRONTEND=none` as environment vars? That's what puppet devs are [doing](https://github.com/puppetlabs/puppet/blob/master/lib/puppet/provider/package/apt.rb).

**Comment by ferki** [comment]
Sure, I'm fine with using these environment settings for all commands. Perhaps it can be split out somewhere comfortably to avoid too much repetition.

@mestia: I took a quick look at the code. What do you think about adding `-o Dpkg::Options::=--force-confold` option to all `apt-get` calls as well (=not just for `install` calls)? Would that make sense too?

**Comment by mestia** [comment]
According to the [Debian handbook](https://debian-handbook.info/browse/buster/sect.automatic-upgrades.html), the defaults should be `-o Dpkg::options::="--force-confdef" -o Dpkg::options::="--force-confold"`  but it would be useful to be able to override it or may be to have 2 different modes - the default one and one with `-o Dpkg::Options::=--force-confnew`.

The meanings of different -foce-conf* options:
`--force-confold:` do not modify the current configuration file, the new version is installed with a .dpkg-dist suffix. With this option alone, even configuration files that you have not modified are left untouched. You need to combine it with --force-confdef to let dpkg overwrite configuration files that you have not modified.
`--force-confnew:` always install the new version of the configuration file, the current version is kept in a file with the .dpkg-old suffix.
`--force-confdef:` ask dpkg to decide alone when it can and prompt otherwise. This is the default behavior of dpkg and this option is mainly useful in combination with --force-confold.
`--force-confmiss:` ask dpkg to install the configuration file if it’s currently missing (for example because you have removed the file by mistake). 
https://raphaelhertzog.com/2010/09/21/debian-conffile-configuration-file-managed-by-dpkg/

**Comment by ferki** [comment]
Thanks for the detailed answer!

I think it's best to deal with the bug and setting the proper environment on this issue then, and then handle the various `-force-conf*` options separately another time.

**Comment by mestia** [comment]
Yes, totally makes sense, the special cases can be forced with something like run "`DEBIAN_FRONTEND=noninteractive apt-get install -o Dpkg::Options::=--force-* $pkg`" anyway. Thanks!

**Comment by ferki** [comment]
Hmm, interestingly enough I can't reproduce this with a current Ubuntu 20.04 system. I downloaded the official ISO and booted into it with a VM.

I can remove the `vim` package with this:

```
rex -d -H 192.168.122.171 -u root -p ubuntu -e 'pkg "vim", ensure => "absent"'
```

It seems there might be some other factors involved in this story, and it would be good to know what it is causing a problem in your case.

In general, I don't mind setting

```
APT_LISTCHANGES_FRONTEND=none DEBIAN_FRONTEND=noninteractive APT_LISTBUGS_FRONTEND=none
```

as default environment for Ubuntu/Debian package operations though.

**Comment by mestia** [comment]
You need a package which would start a debconf prompt on removal. Vim doesn't have that as far as I see.
Just try it with libnss-ldapd or slapd or mysql-server. slapd and mysql-server show interactive debconf prompt on install.

**Comment by ferki** [comment]
> You need a package which would start a debconf prompt on removal. Vim doesn't have that as far as I see.
> Just try it with libnss-ldapd or slapd or mysql-server. slapd and mysql-server show interactive debconf prompt on install.

Yeah, I figured that out later and tried `libnss-ldapd`, but it still didn't happen in my case. I'll try some of the rest in a VM, thanks for the tips!

**Comment by ferki** [comment]
Oh, got it finally :facepalm: The key step I missed is I have to install the package manually, and then try to remove it with rex. In that case it will get stuck while running `apt-get -y remove libnss-ldapd` becaues it waits on a prompt.

So now I can also confirm the buggy behavior, and verify the fix.
