### ISSUE TITLE
Wrong _binary_md5 behavior on *BSD when filename looks like a md5 command output

### ISSUE THREAD

**Issue by Ilya33** [RexOps/Rex#1429]
## Describe the bug

Wrong `_binary_md5` behavior on *BSD when filename looks like an `md5` command output

## How to reproduce it

1. Create file like `md5test = 11111111111111111111111111111111`
2. Get MD5 from this file by `Rex::Commands::MD5::_binary_md5()`
3. The MD5 is wrong

Shortest code example that demonstrates the bug:

Run this test on *BSD

```perl
use strict;
use warnings;

use Test::More tests => 1;
use Rex::Commands::MD5;

my $test_file_md5 = Rex::Helper::File::Spec->catfile( '/', 'tmp', 'md5test = 11111111111111111111111111111111' );

my $fh;
open($fh, '>', $test_file_md5) or
    BAIL_OUT("Can't create file $test_file_md5 $!");
print $fh "\x00";
close($fh);

SKIP: {
  skip 'No MD5 binary seems to be available', 1
    if !defined Rex::Commands::MD5::_binary_md5($test_file_md5);

  is(
    Rex::Commands::MD5::_binary_md5($test_file_md5),
    '93b885adfe0da089cdf634904fd59f71',
    'MD5 checksum OK via binary'
  );
}
```

## Expected behavior

We got right MD5 from file

## Circumstances

 - Rex version: 1.12.2
 - Perl version: any
 - OS running rex: any
 - OS managed by rex: OpenBSD, FreeBSD, OSX maybe
 - How rex was installed: any

## Debug log

none

**Comment by Ilya33** [comment]
Changing line 110 in lib/Rex/Commands/MD5.pm
from `($md5) = $exec->exec("md5 '$file'") =~ qr{\s+=\s+([a-f0-9]{32})};`
to `($md5) = $exec->exec("md5 '$file'") =~ qr{\s+=\s+([a-f0-9]{32})\s*$};`
will fix this problem.

**Comment by ferki** [comment]
Nice catch! Would you like to send a PR later with the test and fix?

We may have to put the "strangely named file" in the test directory directly as trying to create one under `/tmp` may fail under Windows (or perhaps we can create it with `File::Temp` instead, just specifying the exact problematic name).
