### ISSUE TITLE
New directories created implicitly by file() have wrong permissions

### ISSUE THREAD

**Issue by dboehmer** [RexOps/Rex#1459]
## Describe the bug

* `file()` creates directories implicitly if given a path with >=1 depth
* those directories get permissions `rwxr--r--` which makes not sense because `r--` without `x` does not allow access to the file created

## How to reproduce it

~~Steps to reproduce the behavior:~~

Shortest code example that demonstrates the bug:

```perl
file( 'inexistent_dir/file', content => '' );
```

## Expected behavior

* directory `inexistent_dir` gets permissions `rwxr-xr-x` or `rwx------` (more conservative)

## Circumstances

 - Rex version: 1.13.2
 - Perl version: v5.32.0
 - OS running rex: Debian 10 Buster
 - OS managed by rex: Debian 10 Buster
 - How rex was installed: `cpanm`

## Workaround

* explicitly create directory beforehand with

```perl
file( 'inexistent_dir', ensure => 'directory', mode => 'go+rx' );
```

**Comment by ferki** [comment]
Interesting case. I couldn't reproduce it locally without a Rexfile (therefore using all defaults):

```bash
$ cd /tmp
$ rex -e "file( 'inexistent_dir/file', content => '' );"
```

I believe there are still some missing details in play.

What mainly puzzles me is I think rex core currently doesn't try to create any missing parent dirs, and it also doesn't set permissions on its own without `mode => ...` (so in that case the target system's umask settings should be in effect upon file creation instead).

I wonder what could possibly alter the behavior in your use case?

- Is there anything special/related in the Rexfile? Perhaps a before file hook that auto-creates the parent dirs if they don't exist yet?
- When Rex creates directories and sets permissions, it should be visible in the debug log. Is there any clue in there?

**Comment by dboehmer** [comment]
Thank you for the fast reply and sorry for the false alarm!

I investigated this further and found that you’re right:
* directories are *not* created implicitly
* directories are created with `rwxr-xr-x`, probably based on `umask`

Probably an artifact from my previous deployment on the server.

**Comment by ferki** [comment]
No worries, I'm glad we figured it out! I even got an idea for a possible feature or extension module to auto-create parent directories :)
