### ISSUE TITLE
When uploading a file with "files" command with a template, double backslashes are replaced with single backslash

### ISSUE THREAD

**Issue by sdondley** [RexOps/Rex#1474]
## Describe the bug

A template containing double backslashes, "\\\\", will have those replaced with a single backslash when the `files` command is used to upload the template.

## How to reproduce it

1. Create a tempalte file with double backslashes
2. upload the file using the "files" command and the template feature
3. double backslashes will be replaced with a single backslash

Shortest code example that demonstrates the bug:

```perl
    file /path/to/example.php,
      content => template('some_template.php',
        ip_address => $ip_address
      ),
      owner => root,
      group => root,
      mode => 644,
```

## Expected behavior

No backslashes replaced

## Circumstances

 - Rex version: 13.2
 - Perl version: 5.24
 - OS running rex: macos, Big Sur
 - OS managed by rex: debian
 - How rex was installed: cpan

~~## Debug log~~

**Comment by sdondley** [comment]
It seems that it only happens when using a file with php tags in it. It'll happen with this example:

```
 <?php
                        && in_array_nocase('\\NonExistent', $opts)
```

**Comment by ferki** [comment]
Hmm, this does sound like the intended behavior actually. `\` is the escape character that makes sure whatever character is following it, is used literally. So `\\` escapes the second `\`, therefore it is rendered verbatim in the resulting text.

Could you provide a sample template content, with actual vs. desired results?

The example doesn't show the feature flags in effect, so it's not clear if you are using `Rex::Template` or `Rex::Template::NG`. As noted in [template](https://metacpan.org/pod/Rex::Commands::File#template) docs, feature flags `template_ng` or anything equal or above `1.3` should force using the latter, and alternatively any other templating module may be used with rex.

The built-in ones are intentionally kept basic and simple, as this is a problem space that is best handled by one of the many existing modules on CPAN. In other words, I personally don't see too much point having our own templating in core when others did it much better already. But it's included, so not that easy to drop.

**Comment by ferki** [comment]
A note/idea for others stumbling upon this in the future: a similar use case is perhaps better approached by separating code and data.

That is, deploying the code on its own as a file (via the `file` command, rsync, upload an extract and archive, or git pull, etc.), and treating the variable part as a configuration file (which is better suited for templating than arbitrary code).
