### ISSUE TITLE
Add documentation on how to access command line args in a task

### ISSUE THREAD

**Issue by ehuelsmann** [RexOps/Rex#1488]
## User story

**As** a newbee user of Rex
**I would like to** see some documentation I can easily find with respect to using command line arguments in tasks
**so I can** get up and running with Rex quickly in a way that I understand and how I'm used to writing locally executed scripts.

## Additional context

As a not-so-newbee user of Rex, I never can find this information, yet it seems very regularly requested. 

## Describe the solution you'd like

The natural place to add such information would be:

https://github.com/RexOps/Rex/blob/df033cee5be8011207df9f5269bb25d74b94550f/bin/rex#L130

Because that's where the fact that arguments can be passed on the command line is (first) introduced to the user too.

## Describe alternatives you've considered

To be honest, I haven't considered any others.

**Comment by ferki** [comment]
Thanks for the issue, @ehuelsmann! I have now added a short example to `bin/rex` about getting task options from the command line.
