### ISSUE TITLE
Rex::Task synopsis mentions Rex::TaskList method that does not exist

### ISSUE THREAD

**Issue by x-qq** [RexOps/Rex#1489]
The Synopsis on the page https://metacpan.org/pod/Rex::Task currently shows:
```perl
 # retrieve an existing task
 use Rex::TaskList;
 
 my $existing_task = Rex::TaskList->get_task('my_task');
```

however, this code does not work because there is no such method in Rex::TaskList.

**Comment by ferki** [comment]
Thanks for reporting this, @x-qq, and thanks for your patience!

Well spotted, the tasklist object needs to be instantiated first, indeed.
