### ISSUE TITLE
[doc] POD for inspect command is out of order

### ISSUE THREAD

**Issue by rwp0** [RexOps/Rex#1535]
### Describe the bug

The format for `inspect` command documentation is scattered around.

https://metacpan.org/pod/Rex::Commands#inspect($varRef)

![Screenshot](https://i.imgur.com/rYYz9Ju.png)

### Expected behavior

Proper POD rendering in MetaCPAN

### How to reproduce it

Read https://metacpan.org/pod/Rex::Commands#inspect($varRef)

### Rex version

1.13.4

### Perl version

5.36.0

### Operating system running rex

Debian 11

### Operating system managed by rex

FreeBSD

### How rex was installed?

cpan client

**Comment by ferki** [comment]
That's also well-spotted, thanks for reporting, @rwp0!

That code example definitely should be indented by an extra space to render it properly. How MetaCPAN would render the doc could be even checked in advance by using their [Pod Renderer](https://metacpan.org/pod2html) tool.
