### ISSUE TITLE
Incorrect "needs" command documentation

### ISSUE THREAD

**Issue by rwp0** [RexOps/Rex#1542]
### Describe the bug

As described in https://github.com/RexOps/Rex/discussions/1538 discussion:

![image](https://user-images.githubusercontent.com/68062695/185739984-09f0b80f-b5a7-4779-9d1f-1cc64170ccd0.png)

### Expected behavior

Documentation could be as follows:

```perl
needs $package, @tasks;

needs 'Package', 'task1', 'task2', ... 'taskN';
```

### How to reproduce it

Type the command put in Code Example in a `Rexfile`.

### Code example

```perl

package main;

task 'one', sub {
  say 'hello from one';
};

task 'two', sub {
  needs main 'one';
  say 'hello from two';
};

```

### Additional context

https://github.com/RexOps/Rex/discussions/1538

### Rex version

1.13.4

### Perl version

5.36.0

### Operating system running rex

Debian

### Operating system managed by rex

FreeBSD

### How rex was installed?

cpan client

**Comment by ferki** [comment]
The screenshotted error happens because `needs` is not imported into the scope of the newly declared `main` package yet, so it throws a syntax error during compile time.

Since `needs` is defined in the Rex::Commands module, the minimum solution is to add `use Rex::Commands;` below `package main;`.

**Comment by rwp0** [comment]
hmm.. that seems to fail with `use v5.36;`
thanks

**Comment by ferki** [comment]
It's a nice find :+1: but a different issue :upside_down_face: 

`use v5.36;` disables the `indirect` perl feature, and that apparently may break some functionality. Quick fix is to add `use feature 'indirect';` after `use v5.36`.

To avoid mixing up topics, it's probably best to open a new bug for any further investigation.
