### ISSUE TITLE
Attempt to free unreferenced scalar error on Windows before perl-5.20.x

### ISSUE THREAD

**Issue by ferki** [RexOps/Rex#1565]
### Describe the bug

Forking from either Rex::Fork::Task or via Parallel::ForkManager results in "Attempt to free unreferenced scalar" errors upon `exit()`-ing from the child process on Windows with Perl versions before 5.20.2 or 5.20.3.

Since the failure is in the last step of the execution, it only affects the termination of the child process. The task running in the child process can still properly do most of its work, including reporting back its own results via internal data structures (exit code, error messages, etc.), which happens before.

The return value of the task may be lost, though. This might need further tests on top of what is in `t/summary.t`.

Since this seems to be related to a reference counting bug in the affected Perl versions, there might be other side-effects too (memory leaks, crashing, etc.).

See details in automated test results on GitHub Actions and/or CPAN Testers.

### Expected behavior

Ideally, there should be no errors reported from forks on Windows.

At least it should be made sure it doesn't cause problems with Rex functionality, for example by adding more tests (especially for the task's return values).

Speculatively, it may be possible to add a non-forking execution model for Windows. The amount of work required for this is unclear, though.

If all else fails, consider dropping Windows support for Perl versions before 5.20.3.

### How to reproduce it

Run Rex tasks, and/or `t/summary.t` on Windows with a Perl version before 5.20.2 or 5.20.3.

### Code example

No specific code example besides `t/summary.t` at this point.

### Additional context

5.20.1 is affected, and it seems to be first fixed on 5.20.3, but I couldn't test 5.20.2 yet.

[Selected Bug Fixes](https://perldoc.perl.org/perl5202delta#Selected-Bug-Fixes) from perl5202delta mentions:

> On Win32, restoring in a child pseudo-process a variable that was `local()ed` in a parent pseudo-process before the `fork` happened caused memory corruption and a crash in the child pseudo-process (and therefore OS process). [GH #8641]

which might be related. It was fixed in 5.22.0 and backported into 5.20.3.

### Rex version

1.13.4

### Perl version

5.20.1

### Operating system running rex

Windows

### Operating system managed by rex

local

### How rex was installed?

dzil install

**Comment by uralm1** [comment]
I've done some tests and what I discovered.

My test env:
```
D:\src\Rex>perl -v
This is perl 5, version 20, subversion 1 (v5.20.1) built for MSWin32-x64-multi-thread
```

1. First, I can't reproduce error in my simple Rexfile. Even with run("dir") it worked.
2. So I started to cut summary.t that showed me errors. This variant:
```perl
subtest "double free" => sub {
  subtest "aaa" => sub {
    Rex::Config->set_exec_autodie(0);
    Rex::Config->set_distributor('Base');
    test_summary(
      task2 => { server => '<local>', task => 'task2', exit_code => 0 },
    );
  };
};

subtest "but this test passed" => sub {
    Rex::Config->set_exec_autodie(0);
    Rex::Config->set_distributor('Base');
    test_summary(
      task2 => { server => '<local>', task => 'task2', exit_code => 0 },
    );
};
```
resulted in:
```
# Subtest: double free
    # Subtest: aaa
[2023-02-07 12:06:25] INFO - Running task task2 on <local>
Attempt to free unreferenced scalar: SV 0x4a65b60, Perl interpreter: 0x3eb0048 at D:\src\Rex\lib/Rex/Fork/Task.pm line 35.
        ok 1 - task2 succeeded
        1..1
    ok 1 - aaa
    1..1
ok 1 - double free
# Subtest: but this test passed
[2023-02-07 12:06:25] INFO - Running task task2 on <local>
    ok 1 - task2 succeeded
    1..1
ok 2 - but this test passed
```
So I started thinking that this error is somewhat linked with nested subtests. :beetle: This is all for today.

**Comment by uralm1** [comment]
I tested with 1.302191 (then upgraded to 1.302192 - no difference). Also tried `use/no Test2::IPC;` as suggested https://metacpan.org/pod/Test::Builder#THREADS, doesn't help.
As simple solution, I suggest to remove outer subtests in summary.t. Can be tested in a loop here. Should I create PR to test it in CI?

**Comment by ferki** [comment]
> I tested with 1.302191 (then upgraded to 1.302192 - no difference). Also tried `use/no Test2::IPC;` as suggested https://metacpan.org/pod/Test::Builder#THREADS, doesn't help.

Thanks for testing and sharing those hypotheses :+1:

> As simple solution, I suggest to remove outer subtests in summary.t. Can be tested in a loop here. Should I create PR to test it in CI?

I agree that looping through the 2x2 test matrix (of the 2 possible task distributors and 2 possible states of exec_autodie config) might be a good idea to side-step the forking-within-nested-subtests problem of the test suite _and_ simplify `t/summary.t` by removing some of the current code duplication in there.

I might be able to play with that soon too, but feel free to beat me to verifying that idea in your own fork and/or in a pull request.

**Comment by ferki** [comment]
@uralm1: I decided to merge the fix based on your idea in order to have a much cleaner report about GitHub Action workflow runs. Thanks for investigating, and suggesting a way forward! :bow: 

It might be nice to come up with a minimal example to reproduce it, and report the problem to Test-Simple upstream as well, so they can also take a look and maybe fix something for the affected Perls if needed.

Also please reopen if required.
