### ISSUE TITLE
t/can_run.t fails on some Windows hosts

### ISSUE THREAD

**Issue by ferki** [RexOps/Rex#1601]
### Describe the bug

On some Windows hosts `t/can_run.t` fails similar to these CPAN Testers reports:

- http://www.cpantesters.org/cpan/report/75aaf40d-6c06-1014-9be8-f295680790a3
- http://www.cpantesters.org/cpan/report/fca34733-6c06-1014-8c70-6ed8680790a3

Apparently a command literally named `I'm pretty sure this command doesn't exist anywhere` is considered as existing in some cases.

According to feedback from @gregoa (thanks! :handshake: ), the `where` command may exit with a return code of `0` even in case of failures, while printing an error message. For example the following (on a German Windows system):

```
>where "I'm pretty sure this command doesn't exist anywhere"
INFORMATION: Es konnten keine Dateien mit dem angegebenen
Muster gefunden werden.
```

### Expected behavior

Recognize those cases when the checker command returns success, but it is actually a failure.

There is already a secondary check to see if the output matches `/^no command in/` to recognize similar cases on Solaris.

### How to reproduce it

1. Run `prove t/can_run.t` on affected systems (apparently non-English Windows?!)

### Code example

See `t/can_run.t`.

### Additional context

Checking for possible error messages on all possible languages despite successful exit code certainly won't scale.

Rex already tries to force English messages by setting `LC_ALL=C`, but that doesn't apply to Windows.

Perhaps it's best to check if the output returned does actually exist as a file, like a real command would do.

### Rex version

1.14.2

### Perl version

5.32.1

### Operating system running rex

Windows 10.0.19042.746 (German language)

### Operating system managed by rex

local

### How rex was installed?

cpan client

**Comment by gregoa** [comment]
On Thu, 03 Aug 2023 11:05:41 -0700, Ferenc Erki wrote:

> According to feedback from @gregoa (thanks! :handshake: ), the
> `where` command may exit with a return code of `0` even in case of
> failures, while printing an error message. For example the
> following (on a German Windows system):
> 
> ```
> >where "I'm pretty sure this command doesn't exist anywhere"
> INFORMATION: Es konnten keine Dateien mit dem angegebenen
> Muster gefunden werden.
> ```

Thanks for coming back to this issue, and sorry for not being able to
provide any further help.

What I've done now is:

- Take the 1.14.2 tarball from CPAN
- Apply the diff from #1602 (on my Debian laptop :))
- Move the directory to the Windows smoke tester (after 3 attempts to
  update FileZilla, oh what a pain), unpack, go to the directory in
  cmd.exe
- `perl Makefile.PL`
- `gmake`
- And run the previously failing test:

```
>prove --verbose t/can_run.t
t/can_run.t ..
1..4
ok 1 - Found checker command
ok 2 - Non-existing command not found
ok 3 - Multiple commands - existing first
ok 4 - Multiple commands - non-existing first
ok
All tests successful.
Files=1, Tests=4,  7 wallclock secs ( 0.14 usr +  0.03 sys =  0.17 CPU)
Result: PASS
```

Hooray \o/

Cheers,
gregor



-- 
 .''`.  https://info.comodo.priv.at -- Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member VIBE!AT & SPI Inc. -- Supporter Free Software Foundation Europe
   `-

**Comment by ferki** [comment]
> Thanks for coming back to this issue, and sorry for not being able to provide any further help.

It was not reported here yet, so I decided to open an issue myself before attempting a fix.

I feel like you provided crucial help by analyzing the failing case on your machine. I do not have access to such systems, so your participation directly enabled me to propose a fix, and which also enables better experience for other users ;)

Thank you!

> What I've done now is:
> [...]
> And run the previously failing test:
> [...]
> Result: PASS
> Hooray \o/

Also thanks for taking extra care and applying the fix locally to provide further feedback this fast! By now I also see the passing results from your CPAN Testers setup:

- http://www.cpantesters.org/cpan/report/2695da91-6e40-1014-bfed-f80a44cb7e91
- http://www.cpantesters.org/cpan/report/2dd8f55a-7c7c-1014-86ff-0b9fea3939d0
