### ISSUE TITLE
Create rex-server - an api to the rex library

### ISSUE THREAD

**Issue by krimdomu** [RexOps/Rex#187]
This server should be an http / rest api server to the rex library. So that it is possible to use Rex from other languages like bash, python, ruby, ...

**Comment by ferki** [comment]
I think the idea is a great fit for a separate repository where it can have its own life. The experiment is already available in [krimdomu/rex-server](https://github.com/krimdomu/rex-server) if somebody would like to actively take it further.

I believe we don't need to keep this ticket open anymore, so I'm closing it.
