### ISSUE TITLE
ideas for the 2.x version

### ISSUE THREAD

**Issue by krimdomu** [RexOps/Rex#267]
# Ideas

This is just an issue to track all the ideas what can be made different with the 2.x version.

These ideas can contain everything 
- from the coding,
- which perl modules to use, 
- the syntax of the rexfiles (which doesn't necessary mean that we will break compatibility, just to see if there are cool ideas), 
- os support
- modules (Rex::Box, CMDB, ...),
- documentation,
- testing,
- and more

**!! This is just brain storming. !!**
Some of these points here may be implemented while others will not be implemented.

The first release of 2.x is planed at sometime in 2015. This will not make the 0.x (soon 1.x) version obsolete. The 1.x version will be maintained for about 4 years (~2017, this is the end of life of rhel/centos 5)

**Comment by ferki** [comment]
I think I'll move this issue to the wiki :)

**Comment by ferki** [comment]
Thanks everyone for the suggestions and ideas so far, you're awesome! :) This discussion has been converted to a [wiki page](https://github.com/RexOps/Rex/wiki/Ideas-for-Rex-2).
