### ISSUE TITLE
inconsistent feel to Command locality

### ISSUE THREAD

**Issue by SvenDowideit** [RexOps/Rex#35]
I started to think that rex commands are 'run' on the remote host. 

until I used 'sync' which is not.

can this be made consistent?

(the reason was that i need to sync data from several hosts to the newly created vm - so rather than doing:

    sync 'sven@quad:/data/home/sven/src/distributedinformation/projects/Perl/FoswikiInstaller/Packages/*', 'foswiki/Packages/';

I've had to resort to:

    run 'rsync -av sven@quad:/data/home/sven/src/distributedinformation/projects/Perl/FoswikiInstaller/Packages/* foswiki/Packages/';

I find the 'run' remote execution of checkout, install and sysctl to be convenient, but it is a bit misleading, as there's no indication for a new reader telling them that some code is local and other code is not.

**Comment by ferki** [comment]
> Don't rush it :)

Well, apologies for the extremely late feedback, we definitely did not rush it ^^

@SvenDowideit: you're right about this inconsistency and we should resolve this at some point. As this would most probably break backwards compatibility, I moved this idea to the [wiki page](https://github.com/RexOps/Rex/wiki/Ideas-for-Rex-2).

ps.: I believe there might be a slight chance doing this with an option like `sync 'from', 'to', {run_remotely => TRUE};`, but this sounds like causing more confusion and adds substantial complexity to the current code. I think it would be wiser to investigate migration possibility to e.g. [File::Rsync](https://metacpan.org/pod/File::Rsync).
