### ISSUE TITLE
Refactor mkfs/mkswap usage

### ISSUE THREAD

**Issue by ferki** [RexOps/Rex#470]
Rex already tries to create filesystems with `mkfs`/`mkswap` (in Rex::Commands::LVM and in Rex::Commands::Partition), so the logic could be extracted to a single place. It would also make a dedicated `mkfs` command possible.

It could also be useful for example when the partition table is created without creating filesystems yet, e.g. because a RAID array needs to be created first.

**Comment by protoCall7** [comment]
Extracted the mkfs logic from LVM.pm and Partitions.pm into Mkfs.pm.
