### ISSUE TITLE
Is public_key really needed?

### ISSUE THREAD

**Issue by szabgab** [RexOps/Rex#478]
Normal ssh in Linux even if the client using it "only" has the private key file. (id_rsa).
Why does Rex require the presence and the configuration of both the private and the public key?
Couldn't the requirement for the public key removed?

**Comment by ferki** [comment]
I believe the rewritten [Authentication chapter](http://www.rexify.org/howtos/book/authentication.html) of the book clarifes how to configure Rex with different authentication methods.

Meanwhile Net::OpenSSH made default where it makes sense (=everywhere, except on Windows).

So to actually answer the original question:

>Couldn't the requirement for the public key removed?

It depends on the connection method being used:
- it can be, and already has been removed when using Net::OpenSSH (default on non-Windows)
- it can't be removed when using Net::SSH2 (default on Windows, optional on non-Windows)
