### ISSUE TITLE
sudo and passphrase on key

### ISSUE THREAD

**Issue by koboltmarky** [RexOps/Rex#494]
Hi,

i use the following configuration wih rex (R)?ex 0.55.1
and Net:SSH2 ( also with net::openssh)

user "xxx";
private_key "/root/.ssh/id_rsa";
public_key "/root/.ssh/id_rsa.pub";
password "xxxxx";
sudo_password "xxxxxxxxxxxx";
sudo "1";
key_auth;

I get the following error:

WARN - Error running task/batch: Wrong username/password or wrong key on 192.168.10.3. at /usr/share/perl5/Rex/TaskList/Base.pm line 273

It seems that there is a problem with the passphrase.

Workaround is to use ssh-agent, for that you have to remove the key_auth parameter:

ssh-agent bash
ssh-add /root/.ssh/id_rsa

**Comment by ferki** [comment]
@koboltmarky @krimdomu: I can't seem to reproduce this issue on Gentoo and with rex-1.3.2. That being said, I was also unable to reproduce it with 0.55.1. Can you please check again if it's still not broken for you?

I created a new key with `ssh-keygen -t rsa -b 4096` as mentioned above, set passphrase on it, and then used it with the following Rexfile:
```
use Rex -base;

set connection => 'OpenSSH';
user 'ubuntu';
private_key '/home/ferki/.ssh/rex494_rsa';
public_key '/home/ferki/.ssh/rex494_rsa.pub';
password 'passphrase';
sudo_password 'ubuntu';
sudo 1;
key_auth;
```

I could successfully log in and run remote commands, both with SSH and OpenSSH connection methods, and both with and without sudo (though I believe sudo settings/behaviour is unrelated to the SSH auth).

**Comment by fr34k8** [comment]
This works

**Comment by krimdomu** [comment]
Due to inactivity and because of the last comment i'm  going to close this issue.
Everyone feel free to open it again if the problem appears again.
