### ISSUE TITLE
Rex::Commands::Rsync requires Expect which isn't a dependency

### ISSUE THREAD

**Issue by dboehmer** [RexOps/Rex#511]
The require is in https://metacpan.org/source/FERKI/Rex-0.55.3/lib/Rex/Commands/Rsync.pm#L57

Please either make Expect a dependency that is gets installed automatically or remove the need for that module to be present.

**Comment by ferki** [comment]
Sadly, there seems to be no (easy?) way to specify OS-specific recommended dependencies. To balance between the many aspects of the problem domain (see also #1416), the recently merged #1417 describes the rsync capability as an optional feature which pulls in the `Expect` module as its dependency.
