### ISSUE TITLE
File tests fail on windows with 0.56.0

### ISSUE THREAD

**Issue by ferki** [RexOps/Rex#514]
Example report: http://www.cpantesters.org/cpan/report/210e16b9-6c01-1014-85e9-e3c547a6cfb2

**Comment by ferki** [comment]
It looks like that the following happens:
- `t/file.t` tries to create a directory with `file ..., ensure => 'directory'`
- `Rex::Commands::File` calls `Rex::Commands::Fs::mkdir`
- since no `mode` option was set, it defaults to `755`
- `Rex::Commands::Fs::chmod` get called with default mode `755`
- `chmod` method of a new `Rex::Interface::Fs` instance gets called
- `exec` method of a new `Rex::Interface::Exec` instance gets called

And if I'm not mistaken, there's no `chmod` command in Windows by default, so it will fail.

@krimdomu: can it be that it works in your isntance because you have stg like cygwin or gnuwin installed?

ps.: it looks like this has been introduced by 3541b827b9864bba8ca5c6e758de037882d25af4, which otherwise fixes handling of the `mode` option.

**Comment by krimdomu** [comment]
I'll test it again with a clean windows installation later this day.

**Comment by ferki** [comment]
@krimdomu: any luck with a vanilla windows installation?

**Comment by krimdomu** [comment]
@ferki yes, i can reproduce this error

**Comment by krimdomu** [comment]
Tests are now running again.

**Comment by ferki** [comment]
Erm, I think it's still a problem with 1.0.0 and probably it would be better to avoid running `chmod` on windows in the first place (or check its existence first with `can_run`) than just skipping tests. I think the problem boils down to [Rex::Interface::Fs::Base#L130](https://github.com/RexOps/Rex/blob/master/lib/Rex/Interface/Fs/Base.pm#L130). The other `ch*` commands are potentially affected as well.

**Comment by krimdomu** [comment]
grmpf, i tested it on my normal windows installation. and this has some cygwin/unix tools in the path (like chmod, chown, ...) so the tests don't fail there :/
