### ISSUE TITLE
sync_up function will replace template variable of *.tpl  

### ISSUE THREAD

**Issue by petersonchen** [RexOps/Rex#519]
Hi , 

I want to upload my rex project files to remote server  , so I use sync_up api to upload current rex project files .

It seems the sync_up api will replace template variables that file extension is tpl , 
so I can't execute Rex from remote server because the contents of rex files is changed.

I know I can use Rsync or rename filename to instead of , but I want to know Is there way to avoid replace template variable using sync_up api ?

Thanks.

**Comment by krimdomu** [comment]
Hi,

this is indeed the sync_up behaviour to automatically parse '*.tpl' files. I've just added an option to this function, you can download the file from github and replace your Sync.pm file from your Rex installation.

Then you can use this:

```perl
sync_up "local", "remote", {
  parse_templates => FALSE,
};
```

The file: https://raw.githubusercontent.com/RexOps/Rex/ed0e7203738b2b2331b497c10d2c8b873685b5d6/lib/Rex/Commands/Sync.pm

HTH,

Jan
