### ISSUE TITLE
make Text::Glob a dependency instead of copy-pasting

### ISSUE THREAD

**Issue by ferki** [RexOps/Rex#524]
Text::Glob has been copy-pasted as Rex::Helper::Glob which leads us to some weird issues, like:
- multiple version strings across the distribution
- different coding standards (like missing `use warnings;` pragma)
- no updates for the copy-pasted version

Can't we just list Text::Glob as a dependency for Rex?

**Comment by krimdomu** [comment]
Yes, but we have to build a package for this

**Comment by krimdomu** [comment]
perl-Text-Glob is now packaged for the next release.
