### ISSUE TITLE
When querying cmdb and the query name is not exist , msg "Odd number of elements..." was prompt  on console

### ISSUE THREAD

**Issue by petersonchen** [RexOps/Rex#529]
Hi , 

When querying cmdb and the query name is not exist , the below message will be shown on console.

Odd number of elements in anonymous hash at /usr/share/perl5/vendor_perl/Rex/Value.pm line 19.

RexVersion - 0.57.0

**Comment by krimdomu** [comment]
Hi,

thank you for the report. I'll take a look at it.

**Comment by krimdomu** [comment]
Hi,

this will be fixed with the next release.
