### ISSUE TITLE
Possible heavyweight dependencies

### ISSUE THREAD

**Issue by ferki** [RexOps/Rex#538]
`dzil listdeps` shows `Test::mysqld` and `Config::Augeas` as dependencies now, but it looks like they cannot be installed without also installing MySQL or Augeas.

I think we can make `Test::mysqld` as an optional dependency, but I'm not yet sure how to avoid pulling in Augeas. One solution could be to have `Rex::Commands::Augeas` as an external module again (in the rex-recipes repo?) instead of part of core.

**Comment by krimdomu** [comment]
Config::Augeas is no problem, i will remove the hard dependency. Config::Augeas is only used when running local. I'll chane it to test if running local and Config::Augeas is available (if not fallback to augtool)

I'll also change the hard dependeny to Test::mysqld. This is only a dependency in t/db.t. There is already code to skip the tests but dzil sees the "require Test::mysqld" and thinks this is a hard dependeny.

**Comment by krimdomu** [comment]
Okay, this is now solved. Thanks for the hint :+1:

**Comment by ferki** [comment]
@krimdomu: cool! looks like early in the morning I couldn't spot the easy fixes :) thanks for taking care of this! :+1:
