### ISSUE TITLE
hide passwords in debug output

### ISSUE THREAD

**Issue by ferki** [RexOps/Rex#554]
We often ask for debug output of a rex run during support cases, and we always have to give the warning to remove sensitive data from it first. We could help this step by providing a `--hide-passwords` or similar CLI option.

Of course, `sensitive data` might mean different things for different users, but still, hiding some of the common cases might help streamlining the support cases. That means we should document what is hidden, so people can decide if they want to remove more stuff before sending the debug output.

Alternatively we could create an `anonymizer` for debug output, which can be applied to debug outputs just before sending them.

**Comment by petersonchen** [comment]
+1 

I need this feature as well , I develop some task or libs and share with my MIS team , when run task failed ,  I want to clarify the issue  but  I don't want to ask him to run with -d  , because It's difficult to explain and to ask him to remove passwords in log file everytime.

**Comment by krimdomu** [comment]
There is now a new function inside the Rex::Logger module. 

```perl
Rex::Logger::masq("This is data: %s -> %s", "sensitiv-data", "more-sensitiv-data");
```

This will replace the sensitiv data with stars (*). 

I have added this function to the places where i know that we will print out sensitiv data. If there are some places i didn't found yet, please open an issue for them.
