### ISSUE TITLE
Prevent silently accepting and installing unsigned packages

### ISSUE THREAD

**Issue by abeverley** [RexOps/Rex#559]
Hi guys,

Just dropping this in here, as much as a reminder for me to look at sometime (I don't have the time now).

From the code, it looks like when installing a package, a force install is always done (?). Similar to the discussion on #546, I don't think this should be the default. For example, if there was a problem authenticating the package, then you wouldn't normally want to force install. As it stands, this will happen silently, and you would know no better that there was a problem.

**Comment by ferki** [comment]
hi @abeverley, there are multiple different methods to install packages:
```perl
install 'package';
install 'package', version => '0.1.2';
install [qw(package1 package2)];
pkg 'package', ensure => 'present';
pkg 'package', ensure => '0.1.2';
pkg 'package', ensure => 'latest';
pkg [qw(package1 package2)], ensure => 'present';
pkg [qw(package1 package2)], ensure => 'latest';
...
```

Internally they are handled in slightly different ways, and it might be the case that some form or the other tries to install a package even when it was already installed (and there's also some differences in how different OSes are handling those cases). On one hand those cases have to be improved via documentation, and on the other hand we need to make sure that they doing what they expected to do. We already cleaned up unnecessary forced reinstalls in some cases, but of course we might have missed some of them.

Do you remember which form (and which rex version) did you use when you had this forced reinstall?

**Comment by krimdomu** [comment]
@ferki the problem he mentioned is that rex installs packages even if the gpg keys which which the package is signed is not registered to the system.

**Comment by ferki** [comment]
@jfried: ah, thanks for the clarification! For some reason I missed the "authenticating the package" part, and I though this is similar to "package is always reinstalled with `ensure => ver.si.on`" (which is still the case with `ensure => 'latest'`, but that's kind of expected as it uses `&update` internally).

ps.: can we change the summary to "warn about unauthenticated package installs" or similar that describes the issue more precisely?

**Comment by krimdomu** [comment]
for me the renaming is okay. But we can also name it more globaly to something like "Define the behaviour of package installation".

This would then cover global configuration options to configure the package installation by many aspects. Like 
* forcing package updates/downgrades
* forcing installation of unsigned packages
* forcing installation of wrongly signed packages
* ...

as much as the underlying package management system can handle.

**Comment by ferki** [comment]
Good idea, though I think it would be wise to handle those in smaller steps separately, optionally referring to this issue. This issue looks like intended originally to be about checking gpg keys for packages and provide a way to avoid silently accepting them - let the title express this.

**Comment by abeverley** [comment]
Thanks guys. Firstly, I should say that I haven't looked at this in detail, hence the lack of a patch and/or specific details. I'll do this when I get a moment.

I did specifically notice this with regards to unsigned packages. *However*, there are other reasons why a package might not be installed without prompting (eg. problems with dependencies, unexpected files, unexpected conditions etc). It just occurred to me that one might not want a package to be force-installed in these circumstances.

Happy to look at this in more detail later. I just wanted to log it whilst I remembered.

Thanks,

Andy

**Comment by abeverley** [comment]
So, I actually think the issue title should be as it was originally, not specifically for unsigned packages ;-)

**Comment by abeverley** [comment]
Again, I'll look at this in more detail later, but this was the one particular line that concerned me:

https://github.com/RexOps/Rex/blob/master/lib/Rex/Pkg/Debian.pm#L31

```--force-yes``` will override any problems when installing a package. From the manual:

```
--force-yes
           Force yes; this is a dangerous option that will cause
apt to continue without prompting if it is doing something
potentially harmful. It should not be used except in very
special situations. Using force-yes can potentially destroy
your system!
```

Maybe rex is a "special situation"!

**Comment by abeverley** [comment]
Okay, what I reckon we need here is an option to force. The default should be to not, as it can lead to undesirable situations. In the case of Debian/Ubuntu, ```-y``` should always be used, but the option ```--force-yes``` should not be used by default. This leads to the following:
```
-y, --yes, --assume-yes
    Automatic yes to prompts; assume "yes" as answer to all prompts and
run non-interactively. If an undesirable situation, such as changing a held
package, trying to install a unauthenticated package or removing an
essential package occurs then apt-get will abort.
```
This seems like the right thing to do by default. I.e. never prompt, but die if something nasty is potentially going to happen, unless overridden.

Thoughts? How does this fit with other package providers?

**Comment by abeverley** [comment]
Sorry, I realise I haven't answered the comment above about which command I used. It was ```pkg 'package', ensure => 'present';```
However, looking at the source code. all the commands are treated with ```--force-yes```

**Comment by ferki** [comment]
@abeverley: thanks for the followup! In that sense of "forced package installation" my question turned out to be not that important, sorry for confusing your issue with another similar one we had.

I think in relation to `apt-get` options you're right, and probably the `-y` (`--assume-yes`) would be enough for most of the unattended installs. Perhaps `--force-yes` could be made into an option for those who still want that behaviour.

Other package management modules seem to have the right options as far as I can tell.1

Changing this possibly breaks backward compatibility, but it should only affect those adventurous souls who liked to live dangerously :)

@krimdomu: what's your opinion about dropping (or only optionally enabling) `--force-yes` from `Rex::Pkg::Debian`? It looks like to have been carried around for a while, but might be relatively safely omitted (e.g. require people to be explicit about forcing potentially dangerous operations - either via specifying an option, or requiring to write "unsafe" code by themselves).

**Comment by abeverley** [comment]
Thanks, seems like a good idea to me. I'd be surprised if anyone is actually relying on that behaviour, and if they are then they are driving wildly in the fast lane ;-)
Nonetheless, it should probably be a configurable option.

**Comment by abeverley** [comment]
Great, thanks.

**Comment by ferki** [comment]
@abeverley: no problem, thanks for spotting it! Will be available with the next release.
