### ISSUE TITLE
openwrt tests fail completely

### ISSUE THREAD

**Issue by krimdomu** [RexOps/Rex#576]
currently the openwrt tests fail more or less completely

**Comment by ferki** [comment]
Looks like the remote shell (ash) on OpenWrt needs the `no_tty` feature flag.

**Comment by ferki** [comment]
So, it is the dropbear ssh server (which is default on OpenWrt) that needs the `no_tty` feature flag from Rex - it works fine when OpenSSH server is used. I'm gonna update the documentation about it.

**Comment by ferki** [comment]
So, actually it looks like the `no_tty` feature flag is needed, at least with the OpenSSH connection method.

**Comment by ferki** [comment]
[Updated docs](RexOps/rexify-website@9c792038a76634bca81bb6749e8fcbcaad16fd8d) and rex-build tests:
- [updated sshd detection](RexOps/rex-build@4174b38fc7e0fc600aaf6b2530627369f714eaaf)
- [using 1.0 feature flag during preparation](RexOps/rexbuild@510ad02da94fb5229c54eb31319fe53268a311c3)
- [adding block-mount dependency for swap handling](RexOps/rex-build@f8e734f07e7c6683a70bd1f9967f6a711883e3a8)
