### ISSUE TITLE
Instructions on how to update symlinks

### ISSUE THREAD

**Issue by mklette** [RexOps/Rex#591]
Hi,

our workflow ran fine until Rex 0.44.6 but skips important steps when running with recent versions. We use a workflow like this:
 * deploy to unique directory
 * run checks against new code
 * update 'current' symlink to refer to new code's directory
 * run post-deploy actions

Commit 7964964ad82fb16b149f5caba923dbfd27722bb9 seems to introduce the responsible changes, but I miss the intention here:
 * Symlinks aren't changed if target path is already a symlink
 * I can't delete the symlink in advance as only files are respected by unlink

How would I handle above workflow with newer versions of Rex? Any hints or explanations for the new behaviour are much appreciated!

Cheers,
Mathias

**Comment by krimdomu** [comment]
Hi @mklette,

thank you for the report. This is indeed a bug. The above fix should fix it. If you want to test the fix, you can download the file from:
https://raw.githubusercontent.com/RexOps/Rex/f7dfb87dd6614161a5ee1482aca88ea8515b4633/lib/Rex/Commands/Fs.pm

You can just replace the Rex/Commands/Fs.pm file from your installation with this. 

This fix will be included within the next release.

**Comment by ferki** [comment]
We might also need to check the `unlink` functionality, but I think calling `run "rm /path/to/symlink"` might be used as a workaround for deleting symlinks (haven't tested yet though).

**Comment by krimdomu** [comment]
@ferki you're right. there was also a bug in the unlink() function.

@mklette the new file is now here: https://raw.githubusercontent.com/RexOps/Rex/5c64f48a3c2f6796b3e35caa8e62baa01612aaf0/lib/Rex/Commands/Fs.pm

**Comment by mklette** [comment]
@krimdomu Works perfectly with the latest version! Thanks for the quick response!!

Any clue of when your next release will be scheduled?

**Comment by krimdomu** [comment]
@mklette this or next weekend i think.
