### ISSUE TITLE
syntax and manual page corrections

### ISSUE THREAD

**Issue by mestia** [RexOps/Rex#598]
Hi, 
lintian - Static analysis tool for Debian packages has detected a few syntax errors in the man pages.
here is the patch:
http://anonscm.debian.org/cgit/pkg-perl/packages/rex.git/tree/debian/patches/fix_syntax.patch

Also normally a man page should have the "NAME" section, which is parsed by lexgrog and used to generate a database that's queried by commands like apropos and whatis. 
The current man page of rex doesn't have such a section. This patch solves this problem.
http://anonscm.debian.org/cgit/pkg-perl/packages/rex.git/tree/debian/patches/adjust-pod-syntax.patch
Though the DESCRIPTION is optional, I just thought that it fits there.

Thank you, 
Alex

**Comment by ferki** [comment]
@mestia: thanks for the patches! I'm going to merge them from the remote you linked.

**Comment by ferki** [comment]
@mestia: your patches are now merged for the upcoming 1.1.0 release, and I also added you to the list of contributors. Thanks for the doc clean up!
