### ISSUE TITLE
Rex doesn't exit when there is a syntax error

### ISSUE THREAD

**Issue by kablamo** [RexOps/Rex#622]
It hangs forever and I have to do control-c.  A minor low priority thing, I know.

**Comment by ferki** [comment]
@kablamo: thanks for the report! Could you provide an example for us to reproduce this? Also which version of Rex you used when experiencing this? There is already a syntax checking logic before trying to use modules/Rexfiles, it probably just misses a corner case we'd like to fix.

**Comment by ferki** [comment]
@kablamo: do you have any more details on this? Can you share an example Rexfile which causes this on your machine, along with a debug output?

**Comment by krimdomu** [comment]
When there is a syntax error, rex is doing a recursive scan over the directory where the Rexfile is and try to do a syntax check on all "Rexfile" and "*.pm" files to print out all syntax errors.

Maybe this is the problem in your case. Do you have a large directory tree?

**Comment by kablamo** [comment]
Yeah it happens when I introduce any kind of syntax error.

Yes I do have a large directory tree.  I bet thats the problem.  I'm using Carton so I have a bunch of modules installed in ./local/lib/perl5.  Maybe rex should just look at the lib directory?  Hmm or it could skip ./local/lib.  Or it could skip anything in .gitignore.

**Comment by ferki** [comment]
@kablamo: I believe this was fixed on #778. Can you confirm that?

**Comment by ferki** [comment]
As far as I can tell, it should be already fixed on #778, so closing this. If there are any further troubles with syntax checking, please open a new issue.
