### ISSUE TITLE
Can't use ALL with after_task_finished()

### ISSUE THREAD

**Issue by kablamo** [RexOps/Rex#629]
Here is the error I get:
```
[2015-04-12 20:44:32] INFO - Can't add after_task_finished (?^:.*), as it is not yet defined
see (eval 483) line 101
```

Even though I put it at the end of my Rexfile.

**Comment by krimdomu** [comment]
@kablamo i just tried it and it seems that this is only a faulty message. The hook gets executed. We're going to fix this.

Thanks for the report.

**Comment by kablamo** [comment]
I agree with your findings with one exception: the hook doesn't get executed if the task runs on the localhost.

**Comment by kablamo** [comment]
Oh! ALL means all tasks in the current file.  I thought it meant all tasks everywhere.  Please ignore my previous comment about it not getting executed for localhost.

**Comment by krimdomu** [comment]
@kablamo yes, `ALL` means in the current namespace. So if some 3rd party modules use `ALL` it doesn't compromise others.

**Comment by kablamo** [comment]
@krimdomu is this fixed?  I can't seem to recreate it now.  Don't know what I did.

**Comment by krimdomu** [comment]
@kablamo 

ah thanks to remind me. no this is not fixed yet.
