### ISSUE TITLE
exec_autodie prints an error and a warning

### ISSUE THREAD

**Issue by kablamo** [RexOps/Rex#635]
I really only want one i think?

**Comment by ferki** [comment]
hi @kablamo, can you please attach an example output? I only got errors so far with my tries, but no errors.

**Comment by kablamo** [comment]
[2015-04-20 17:17:31] INFO - Running task grep:access on <local>
[2015-04-20 17:17:33] ERROR - Error executing task:
[2015-04-20 17:17:33] ERROR - Error executing: grep '500asdfasdf' /var/log/nginx/nginx-access.log.
Output:

[2015-04-20 17:17:33] WARN - Error running task/batch: Error executing: grep '500asdfasdf' /var/log/nginx/nginx-access.log.
Output:

**Comment by kablamo** [comment]
So what I'm seeing is from:
1. warning: https://github.com/RexOps/Rex/blob/master/lib/Rex/CLI.pm#L639
2. error: https://github.com/RexOps/Rex/blob/master/lib/Rex/Interface/Executor/Default.pm#L60

**Comment by ferki** [comment]
@kablamo: I guess the warning message can be suppressed if `exec_autodie` is enabled.

In my opinion this is closer to the expected output when requesting that feature, plus also keeps the notification about the problem on the screen when stg is executed via the `-e` CLI option (so no task involved at all).

@krimdomu: do you see anything wrong with disabling the second message in this case?

**Comment by krimdomu** [comment]
@ferki 
suppressing the message if `exec_autodie` is enabled in lib/Rex/CLI.pm seems to be the right way.

**Comment by kablamo** [comment]
Children should exit before the if statement in Rex::CLI.  This problem will be resolved by https://github.com/RexOps/Rex/pull/697

**Comment by ferki** [comment]
Fixed in #697
