### ISSUE TITLE
wishlist: tab completion

### ISSUE THREAD

**Issue by kablamo** [RexOps/Rex#636]
I'm 87% sure this is possible.  It would be fun to get bash tab completion for server names, server groups and tasks.

**Comment by ferki** [comment]
@samuelet posted an initial version of this over at our [google group](https://groups.google.com/forum/#!searchin/rex-users/bash$20completion/rex-users/HlIbyKYJu2c/LnSkTblEj5gJ)

@samuelet, @krimdomu: I think we can try to integrate it into the core, right?

**Comment by krimdomu** [comment]
@ferki yes, i think this is a good idea :+1:

**Comment by petersonchen** [comment]
It would be great if rex add this feature.

**Comment by samuelet** [comment]
The rex completiton script still works with the last rex version but i have to say that it could be a little slow during completition because, on every tab pressing, it launches 'rex -Tv' (which is not enough fast for this purpose). Implementing a cache mechanism could mitigate the problem.

**Comment by kablamo** [comment]
Hmm yeah you are right -- its too slow.  Caching is a good idea.  I will add a cache mechanism to the bash script and submit a pr.

@samuelet whats up with the first line of code? `have rex && `  Is that pseudo code?  I'm not familiar with the `have` command?

**Comment by samuelet** [comment]
have is an internal function that checks if a command exists.

**Comment by kablamo** [comment]
@samuelet oh.  So that means i can't just source the file.  I gotta put it in /etc/bash_completion.d/ and source /etc/bash_completion.  Which means people need root access to use it though...  

We could remove that `have()` and then root access would not be required.  I find that tempting.

**Comment by kablamo** [comment]
This was merged.  
https://github.com/RexOps/Rex/pull/652#issuecomment-97962565

The main thing thats left is that the bash script is not installed anywhere.  leaving that for another day/pr.
