### ISSUE TITLE
Problems with file manipulation with Net::OpenSSH and sudo

### ISSUE THREAD

**Issue by krimdomu** [RexOps/Rex#640]
Currently there are problems when editing files with Net::OpenSSH connection mode and sudo enabled.
The problems seems to occur on Fedora 21.

If you are hit by this bug a workaround is to switch back to Net::SSH2 connection mode:

```perl
set connection => "SSH";
```

**Comment by ferki** [comment]
Is Fedora 21 the OS of the remote or the local machine?

**Comment by krimdomu** [comment]
the remote machine

**Comment by krimdomu** [comment]
After a few tests, this is not a bug in rex. There seems to be some configuration on a base fedora installation that prevents rex from editing files in /etc. If i copy `/etc/hosts` to `/tmp/hosts` it can be manipulated without any problems.

i have to dig deeper what fedora is doing there.

**Comment by krimdomu** [comment]
hmpf too early to close... With the mentioned workaround the files in /etc can be manipulated...

**Comment by krimdomu** [comment]
this fix might also solve #199 without the patch from Net::SFTP::Foreign (salva/p5-Net-SFTP-Foreign#5).  Many thanks to @salva for the workaround he added to Net::SFTP::Foreign. I wasn't aware of this until the link from @petersonchen in #605.

**Comment by ferki** [comment]
@krimdomu: nice :+1:
