### ISSUE TITLE
download command will produce a warning message if no local file is specified 

### ISSUE THREAD

**Issue by petersonchen** [RexOps/Rex#647]
According the api http://www.rexify.org/api/Rex/Commands/Download.pm.html

 If no local file is specified , the function will work normal , but I try the below code 
     download("/root/test.txt") 
will produce a warning message
    Use of uninitialized value $path in pattern match (m//) at /Library/Perl/5.16/Rex/Helper/Path.pm line 146.

== environment ==
Rex v1.1.0

**Comment by krimdomu** [comment]
Hi @petersonchen 

thank you for this report. This will be fixed in the next release.
