### ISSUE TITLE
PATH environment problem

### ISSUE THREAD

**Issue by petersonchen** [RexOps/Rex#657]
Hi , 

in /etc/profile , I export some path to PATH environment , 
so I use source_global_profile(1) command  to make sure my run command  will work fine.

But this does not work , because rex reset PATH environment after sourcing /etc/profile.

the workaround for me is sourcing again before run command
     run(". /etc/profile >/dev/null 2>&1 ; mvn -version");

== part of /etc/profile ==
export M2_HOME=/usr/local/apache-maven
export M2=$M2_HOME/bin
export PATH=$M2:$PATH

== part of log ==
[2015-05-03 16:27:06] DEBUG - SSH/executing: . /etc/profile >/dev/null 2>&1 ; LC_ALL=C ; export LC_ALL; PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/pkg/bin:/usr/pkg/sbin; export PATH; mvn -version

**Comment by krimdomu** [comment]
Hi @petersonchen 

thanks for this report. At first i thought it was a bug, but after looking at the code it is wanted. Rex cleans up the PATH variable before executing things. This prevents some bugs if (for example) someone has a custom *ifconfig* command (or other commands rex uses) in his custom PATH.

You can disable this with the feature **no_path_cleanup**.

```perl
use Rex -feature => ['source_global_profile', 'no_path_cleanup'];
```

With this, Rex will use the PATH settings from your /etc/profile.

HTH,

Jan

**Comment by petersonchen** [comment]
Hi @krimdomu ,

Thanks for your explanation , I'll use no_path_cleanup feature flag,

by the way , congratulate for Rex v1.2.0 is released. ^_^
