### ISSUE TITLE
running 'rex -T foo' should not show server groups

### ISSUE THREAD

**Issue by kablamo** [RexOps/Rex#678]
running 'rex -T foo' should not show server groups

**Comment by ferki** [comment]
Why not? :) Why should it be different from `rex -T`?

**Comment by kablamo** [comment]
If you typed in a task namespace, the question you want answered is what tasks match that namespace.  
You have a point about consistency I guess though.  I think I'll close this. 

But I think in the new cml ui, displaying tasks, displaying batches, displaying servers should all be separate commands.  displaying all that info in one screen from one command means that most of the information displayed is not relevant to what the user is looking for.
