### ISSUE TITLE
Use =head2 POD directive for Rex class methods and exported DSL functions

### ISSUE THREAD

**Issue by cpanxaoc** [RexOps/Rex#685]
The POD style for Rex class methods and subclass exported DSL functions is to currently use `=over/=back` blocks with `=item` directives for individual methods or exported DSL functions.  This works, however, if you use `=head2` directives instead of `=item` directives for these, they'll be listed in Contents section for search.cpan.org/MetaCPAN, as well as being more strongly highlighted when viewing POD in a browser.  The `=over/=back/=item` blocks should still be used for method/function arguments, but it would be nice if, when you viewed a Rex class online, you immediately see what DSL functions are available in that class in the "Contents" box of SCO/MetaCPAN.

**Comment by ferki** [comment]
@cpanxaoc: that sounds great! We actually wanted to achieve the same with the API docs on rexify.org. I guess we can use the same `=head2` directives to drive content generation in `misc/create_pod.sh` as well (which is a bit cryptic script and only generates sensible output with perl-5.14.4, so it could definitely use a revamp).

**Comment by ferki** [comment]
@cpanxaoc: thanks again for this contribution! I merged it manually after squashing your commits together and slightly rewording the commit message.
