### ISSUE TITLE
upload or file command not working properly for some server

### ISSUE THREAD

**Issue by pmverma** [RexOps/Rex#695]
I am using Rex and having some problem when trying to send file to a remote host.

1.I tried with upload command

```
`upload '/root/rex_project/Rexfile/temp.log', '/tmp/';`
```

  The file was not uploaded.

  Please see the debug log: http://pastebin.com/XqUPunQA
1. I tried with file command
   
   ```
   `file '/tmp/temp.log', source => '/root/rex_project/Rexfile/temp.log';`
   ```
   
   The file was not fully uploaded, only an empty file was created.

Please see the debug log: http://pastebin.com/0mS4Szfs

Does anybody have same kind of problem?

My Rex:
CentOS 6.4 64 bit, 
Rex 1.2.1

**Comment by ferki** [comment]
@pmverma: thanks for the report! I'm just adding some notes based on our IRC conversation earlier:
- `upload` command was used with sudo
- `file` command was used as normal root user
- using Net::OpenSSH seems to solve the problem
- Net::SSH2 version was 0.45
- only one specific server showed the symptoms, others were managed successfully

**Comment by pmverma** [comment]
@ferki: great comment.
I will try add as much as information later times ;)

And yeah only one specific server showed the symptoms, others were managed successfully.
But currently solved by installing Net::OpenSSH.

**Comment by ferki** [comment]
@pmverma: do you have some further info about this? Can you share which OS was running on the remote server which showed this behaviour?

Also, can you please try again with rex-1.3.2 and Net::SSH2 against the same failing server again?  This release might have fixed this issue as well.

**Comment by pmverma** [comment]
@ferki: Sorry for my late reply.

The remote OS was Redhat Enterprise Linux 6.2 64 bit.
                                 libssh2-1.2.2-7.el6_1.1.x86_64
                                 openssh-server-5.3p1-70.el6.x86_64

I just tried with rex-1.3.2 and Net::SSH2 (by removing NET::OpenSSH), the problem still exists while others remote OS RHEL6.2 working properly.

Do you need other info by which I can help you?

**Comment by fr34k8** [comment]
Do you use pass or keyauth with the Servers ?

**Comment by pmverma** [comment]
@fr34k8: I use pass.

**Comment by ferki** [comment]
@pmverma: is this still affecting you with recent versions? Can you check it again with rex-1.4.0 and a recent Net::SSH2, please?

**Comment by pmverma** [comment]
Closing as I am no longer working on that project and nobody has reported any similar issues.
