### ISSUE TITLE
pass filename of `file` command through `glob` function

### ISSUE THREAD

**Issue by ferki** [RexOps/Rex#712]
Contructs like this:
```perl
file '/tmp/test1', ensure => 'directory';
file '/tmp/test1', ensure => 'directory';
```
can be simplifed like this:
```perl
file [ qw( /tmp/test1 /tmp/test2 ) ], ensure => 'directory';
```
by relying on the fact that `file` command accepts an array reference as its first argument. Following up on that idea, it can be further simplified to:
```perl
file [ glob('/tmp/test{1,2}') ], ensure => 'directory';
```

I think it would be nice to run the filenames passed via `file` command's first argument through `glob` (regardless if they are given as simple scalars or multiple ones in an array reference), making it possible (and maybe more natural) to write constructs like this:
```perl
file '/tmp/test{1,2}', ensure => 'directory';
```

**Comment by jluis** [comment]
@ferki on https://github.com/jluis/Rex/commit/9b5f94db605581c9bb6d8cb1cc42d59dfaf3a645 I have put test and code to resolve this isue but I am not surte that the filename is santized enohg for glob to proccess.

I don't check for the existence of chars cound make glob stat for the filename ony if there are braces to pas the braces and the text inside to glob.

**Comment by ferki** [comment]
After carefully considering different use-cases and possibilities with @jluis, we decided not to implement this as a feature in Rex. Instead, we're going to document the multiple file creation options, including examples for glob usage, and also warnings about possible pitfalls.
