### ISSUE TITLE
Amazon.pm signature version 4

### ISSUE THREAD

**Issue by fr34k8** [RexOps/Rex#737]
Is it possible to update the Amazon / Cloud to support sig4 ?
http://docs.aws.amazon.com/general/latest/gr/signature-version-4.html

ATM no auth is possible in eu-central-1 (FFM)

**Comment by krimdomu** [comment]
Hi @fr34k8 ,
thanks for the information. I'm going to look into it.

**Comment by krimdomu** [comment]
@ferki 
what do you think, should we use https://metacpan.org/pod/Net::Amazon::EC2 ?
this has a dependency to Moose, so we would need to build Moose packages for some operating systems.

**Comment by ferki** [comment]
@krimdomu: yeah, or maybe just [AWS::Signature4](https://metacpan.org/pod/AWS::Signature4) for now. I see no point in re-implementing that if a reasonably simple/lightweight module is already there. Needs evaluation though, I just found it by a quick search.

**Comment by fr34k8** [comment]
That Sounds good to me.
Just lightwight atm seems legit.

**Comment by krimdomu** [comment]
@ferki @fr34k8 AWS::Signature looks good indeed.

**Comment by krimdomu** [comment]
We have to implement the new signature on our own (in the first run) because AWS::Signature4 has a dependency that Centos5 can't fullfill.

**Comment by fr34k8** [comment]
Please exclude centos 5 and older (in the first run) if possible  @krimdomu @ferki

**Comment by krimdomu** [comment]
@fr34k8 i created an issue branch for this: issue/737. I've added the AWS::Signature4 Module directly to Rex and rewrote the signing function to use this. On my local tests this work, it would be nice if you can verify this.

**Comment by ferki** [comment]
@krimdomu: we can try to work with upstream to make it work on CentOS5, or as a plan B, we can try to override only the problematic methods/functions. Peronsally I would put extra effort in that direction instead of maintaining a yet-another full-blown implementation.

**Comment by krimdomu** [comment]
@ferki 

the problem is, that it depends on a newer libwww-perl. So we need to supply such a newer libwww-perl for CentOS5.

I need to check if this is really needed, or if the author just added these versions to the dependencies. If this is the fact, we can provide an upstream patch to lower the requirements. 

The current patch is just for fr34k8 so that his things work.

**Comment by fr34k8** [comment]
@krimdomu give me a few hours 
@ferki yes this should be an upstream topic.

**Comment by fr34k8** [comment]
@krimdomu quick Test works out of The box.

**Comment by krimdomu** [comment]
added this also to master branch now. the Amazon modul (and also the other Cloud-Modules) needs a refactoring anyway. So we can add this until the refactor.
