### ISSUE TITLE
Wrong domain for box URLs

### ISSUE THREAD

**Issue by arpadszasz** [RexOps/Rex#740]
Several places in the code mention box URLs from [http://box.rexify.org/box/...]( http://box.rexify.org/box/ubuntu-server-12.10-amd64.ova), but the current (working) URLs are from [http://box.linux-files.org/...](http://box.linux-files.org/ubuntu-server-12.10-amd64.ova).

```
$ HEAD http://box.rexify.org/box/ubuntu-server-12.10-amd64.ova
404 Not Found
Connection: close
Date: Wed, 08 Jul 2015 18:00:34 GMT
Server: nginx/1.7.7
Content-Length: 1036
Content-Type: text/html;charset=UTF-8
Client-Date: Wed, 08 Jul 2015 18:00:35 GMT
Client-Peer: 144.76.82.201:80
Client-Response-Num: 1
```

I don't know if this is only a misconfiguration on the **box.rexify.org** domain or the code should be changed to the new domain. Looking forward for some feedback before creating a pull-request. Thanks.

**Comment by ferki** [comment]
@arpadszasz: thanks for repoting this, and sorry for the late reply. Looks like there was a missing redirect in our config, and it should work now:
```bash
$ HEAD http://box.rexify.org/box/ubuntu-server-12.10-amd64.ova
200 OK
Connection: close
Date: Sun, 23 Aug 2015 12:56:31 GMT
Accept-Ranges: bytes
ETag: "52680eb0-1b23ea00"
Server: nginx/1.7.7
Content-Length: 455338496
Content-Type: application/octet-stream
Last-Modified: Wed, 23 Oct 2013 18:00:16 GMT
Client-Date: Sun, 23 Aug 2015 12:56:31 GMT
Client-Peer: 144.76.82.201:80
Client-Response-Num: 1
```
