### ISSUE TITLE
Dependency not listed: Rex::CMDB::YAML depends on Hash::Merge

### ISSUE THREAD

**Issue by ehuelsmann** [RexOps/Rex#741]
The package in the rex repository doesn't list libhash-merge-perl as a dependency for Rex::CMDB::YAML; neither does the prereq listing in dist.ini seem to.

**Comment by krimdomu** [comment]
Hi @ehuelsmann,

thanks for the hint. We're going to fix this. But currently i can't do anything on the computer because my handwrists are injured. So sorry for the delay.

**Comment by ehuelsmann** [comment]
Hi Jan,

Especially in the condition you describe: thanks for letting me know! (And
get well!)

Regards,


Erik.

**Comment by ferki** [comment]
@ehuelsmann: thanks for the issue and for the additional details!

The dependencies are autogenerated by Dist::Zilla during buildtime (e.g. for CPAN), so that's why we don't list it explicitly in `dist.ini`.

We need to add `libhash-merge-perl` to the OS-specific package build instructions though.

**Comment by ferki** [comment]
@ehuelsmann: the nightly builds should already be fixed. Last known issue is to build a 64bit `perl-Hash-Merge` RPM for CentOS 5.

**Comment by ferki** [comment]
All package and nightly builds have finished successfully \o/
