### ISSUE TITLE
Environment error after upgrading to 1.3.2

### ISSUE THREAD

**Issue by ehuelsmann** [RexOps/Rex#742]
Coming from 1.0.1, I just upgraded to 1.3.2 and my "prod" environment (the only one beside "default") stopped working.

Couldn't find anything in the release notes, but adding

````perl
environment "prod" => sub {};
````

Solved my issue

**Comment by petersonchen** [comment]
After the issue #639 ,  I  need to add the code  you provided as well.

**Comment by ferki** [comment]
@ehuelsmann, @petersonchen: can you please share some more info about your original use case? Like how you call rex from the CLI?

Is it something like `rex -E prod task`, but not specifying and environment called `prod` in the Rexfile?

**Comment by ehuelsmann** [comment]
Hi FErki,

Indeed, in 1.0.1, there was no need to define the environments in the
Rexfile; I simply had "server.{environment}.ini" and "cmdb/{environment}".
Then, I'd invoke

   $ rex -E prod task

or

  $ rex -E default task

and it would run using the appropriate targets and configurations.


Regards,

Erik

**Comment by ferki** [comment]
I still think the default behaviour should be to fail in this scenario (an environment is specified on the command line, but not defined in Rexfile), but I also agree there might be a reason to do this (as you presented it too).

So after all I believe a pair of feature flags are warranted here to opt-in for/opt-out from "I know what I'm doing, and I don't care if my environment is undefined, please fall back to `default` environment". Called like `default_environment` and `no_default_environment`.

I think a warning/info message would still be nice in that case, just before falling back to `default` environment. Which can be suppressed by the "empty" environment specification if needed.

@ehuelsmann, @petersonchen: what do you think about this?

**Comment by petersonchen** [comment]
@ferki 

I'm ok with your idea.
Thank you

**Comment by ferki** [comment]
So after an IRC discussion with @ehuelsmann, we think that:
- rex should show a warning, if an environment has been requested on the command line with `-E`, but it is not specified in the Rexfile, as this indicates a potential mistake
- for those, who are doing this intentionally, rex should provide a way to suppress this warning. This can be achieved by specifying an empty/dummy environment in the Rexfile (as pointed out in the opening post). Achieving the same with a feature flag would also require the editing of the Rexfile, but IMHO the dummy environment method is already there, requires no additional complexity, while still clear ebough on the intent.
- rex should preserve the original behaviour to preserve backwards compatibility, so `die()`ing would be too harsh here, but a warning message with recommended action is warranted

See attached PR for proposed solution.
