### ISSUE TITLE
Cannot control services if systemctl is found but systemd is not active

### ISSUE THREAD

**Issue by theappleman** [RexOps/Rex#753]
Running Gentoo with OpenRC as the active init system, however systemd is installed.

Because of the Rex::Service logic and can_run, systemd is always used and cannot be corrected with service_provider_for:
https://github.com/RexOps/Rex/blob/master/lib/Rex/Service.pm

```
[2015-07-27 21:14:19] DEBUG - sudo: exec: perl /tmp/yqusfftmwfpq.tmp '%15_%025004%
18%17%5D%00%15%1FX%3B%1F%3E%2D%3F%0D%21%1FD' 2>/dev/null | sudo  -p '' -S sh -c "L
C_ALL=C ; export LC_ALL; PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/lo
cal/sbin:/usr/pkg/bin:/usr/pkg/sbin; export PATH; which systemctl  "
[2015-07-27 21:14:19] DEBUG - SSH/executing: perl /tmp/yqusfftmwfpq.tmp '%15_%0250
04%18%17%5D%00%15%1FX%3B%1F%3E%2D%3F%0D%21%1FD' 2>/dev/null | sudo  -p '' -S sh -c
 "LC_ALL=C ; export LC_ALL; PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr
/local/sbin:/usr/pkg/bin:/usr/pkg/sbin; export PATH; which systemctl  "
[2015-07-27 21:14:19] DEBUG - /usr/bin/systemctl
...
[2015-07-27 21:14:19] DEBUG - sudo: exec: perl /tmp/eonxqrvqespv.tmp '%09%5B%12%25
%3B%26%2B%1A%1A%5C%0E%0B%0C%40%2F%10%2E%2A3%08%2E%1ER' 2>/dev/null | sudo  -p '' -
S sh -c "LC_ALL=C ; export LC_ALL; PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/b
in:/usr/local/sbin:/usr/pkg/bin:/usr/pkg/sbin; export PATH; nohup systemctl show e
pmd.service | grep LoadState=loaded >/tmp/hxsdjxxevwbc.tmp  "
[2015-07-27 21:14:19] DEBUG - SSH/executing: perl /tmp/eonxqrvqespv.tmp '%09%5B%12
%25%3B%26%2B%1A%1A%5C%0E%0B%0C%40%2F%10%2E%2A3%08%2E%1ER' 2>/dev/null | sudo  -p '
' -S sh -c "LC_ALL=C ; export LC_ALL; PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/loca
l/bin:/usr/local/sbin:/usr/pkg/bin:/usr/pkg/sbin; export PATH; nohup systemctl sho
w epmd.service | grep LoadState=loaded >/tmp/hxsdjxxevwbc.tmp  "
[2015-07-27 21:14:20] DEBUG - ========= ERR ============
[2015-07-27 21:14:20] DEBUG - Failed to get D-Bus connection: Operation not permit
ted

[2015-07-27 21:14:20] DEBUG - ========= ERR ============
...
[2015-07-27 21:14:20] ERROR - Error executing task:
[2015-07-27 21:14:20] ERROR - Service epmd.service not found. at /usr/lib/perl5/ve
ndor_perl/5.20.2/Rex/Service/Base.pm line 40.

[2015-07-27 21:14:20] WARN - Error running task/batch: Died at /usr/lib/perl5/vend
or_perl/5.20.2/Rex/Interface/Executor/Default.pm line 62.
```

My usual technique for testing for systemd is to check the return code, however I don't think can_run does.

```sh
$ systemctl
Failed to get D-Bus connection: Operation not permitted
$ echo $?
1
```

I couldn't think of a way to check for this or fix it without breaking the api.

**Comment by ferki** [comment]
Well, it should be possible to force a specific service provider with [`service_provider_for`](http://www.rexify.org/api/Rex/Commands/Service.pm.html#service_provider_for-os-type-), but I think it would also possible to add one more condition to [this line](https://github.com/RexOps/Rex/blob/master/lib/Rex/Service.pm#L50) for automatic detection.

**Comment by theappleman** [comment]
service_provider_for [appends](https://github.com/RexOps/Rex/blob/master/lib/Rex/Service.pm#L67) to the detected service provider, e.g.:

```perl
service_provider_for Gentoo => "openrc"

=> Rex::Service::Gentoo::systemd::openrc
```

and while this affects me in Gentoo, could other distros install systemd without using it for init?

**Comment by ferki** [comment]
Oh, at first glance, it looks like there's no way to force using the default service provider. My bad, sorry. And it's a good question whether other distros can be hit by this. I guess we can just fix it for all of them regardless if it can happen on them or not.

BTW, out of curiosity, what is the use case of having systemd installed, but not used for init (apart from "just installed, but not rebooted yet")?

**Comment by theappleman** [comment]
Mostly that. The embedded system I'm running this on didn't like the kernel command line change (adding "init=/usr/lib/systemd/systemd"), so it's back to as it was.

Thanks for looking into it!
