### ISSUE TITLE
failing tests

### ISSUE THREAD

**Issue by mestia** [RexOps/Rex#763]
Dear Rex developers, running autopkgtest [0] on Rex debian package revealed a couple of failed tests:
```
t/interface_fs_local.t .......
1..7
ok 1 - created fs interface object
not ok 2

#   Failed test at t/interface_fs_local.t line 13.
not ok 3 - ChangeLog is a file
    
#   Failed test 'ChangeLog is a file'
#   at t/interface_fs_local.t line 15.
#          got: undef
#     expected: '1'
ok 4 - . is a directory
ok 5 - mkdir
ok 6 - rmdir
ok 7 - stat should return undef for non-existent files
# Looks like you failed 2 tests of 7.
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/7 subtests


t/last_command_output.t ......
1..3
not ok 1

#   Failed test at t/last_command_output.t line 12.
#                   'total 16
# -rw-r--r-- 1 root root   29 Aug 19 15:15 MANIFEST
# -rw-r--r-- 1 root root    0 Aug 19 15:15 MANIFEST.SKIP
# drwxr-xr-x 4 root root 4096 Aug 19 15:15 blib
# drwxr-xr-x 3 root root 4096 Aug 19 15:15 lib
# drwxr-xr-x 4 root root 4096 Jun 17 15:06 t'
#     doesn't match '(?^ms:ChangeLog)'
ok 2
ok 3
# Looks like you failed 1 test of 3.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests


    # Bareword "Rex::is_sudo" not allowed while "strict subs" in use at /usr/share/perl5/Rex/Commands/Rsync.pm line 164.
    # /usr/share/perl5/Rex/Commands/Rsync.pm had compilation errors.
    not ok 173 - /usr/bin/perl -wc /usr/share/perl5/Rex/Commands/Rsync.pm exited successfully
```

Thank you, 
Alex

[0] https://pkg-perl.alioth.debian.org/autopkgtest.html

**Comment by ferki** [comment]
@mestia: thanks for the report! We run the same tests (and lot more) before creating our deb files, so it's a bit weird, but there might be some problems packaging.

Can you please attach a link to the package you used when you got the failing test? Also maybe the debian version the problems appeared, and the command with which we can try to reproduce it, please? I'm unfortunately not familiar with `autopkgtest` and I'd like get up to speed with it to make sure we're testing the exact same thing.

**Comment by mestia** [comment]
Hi here are the steps to run autopkgtests on a debianized source.

1. ```aptitude install autopkgtest pkg-perl-autopkgtest```
  
2. ```aptitude install schroot sbuild```
   It is usefull to use a minimal chroot and start with clean minimal system.

3. create the minimal chroot
```
   sbuild-createchroot --make-sbuild-tarball=/srv/chroot/unstable_amd64.sbuild.tar.gz sid `mktemp -d` http://ftp.de.debian.org/debian/
```
4. ```git clone git://anonscm.debian.org/pkg-perl/packages/rex.git```

6. ```adt-run --unbuilt-tree rex  --- schroot sid-amd64-sbuild```

The last step will take a while because it will install all deps, build the package and after run the tests.

**Comment by ferki** [comment]
Ah! So it's not the deb package from `rex.linux-files.org` :)

Looks like the file `ChangeLog` is not there where the tests are expecting it (testing if Rex can recognize something as a file, and testing if an `ls` command's output is looking right). Though it seems it's there in the `git://anonscm.debian.org/pkg-perl/packages/rex.git` repo.

@mestia: do you have an idea why that could happen?

**Comment by mestia** [comment]
Sorry for the late answer.
In case with the ChangeLog file the test (smoke) didn't copy the ChangeLog to the temporary directory, and thus filed. I see now how I can fix it, but of course this is something you shouldn't care about. Sorry for the noise.
But there are still issues like the last one (  Bareword "Rex::is_sudo" ) , I an not completely sure, but it seems like this one can point to a potential problem.
Thank you, 
Alex

**Comment by ferki** [comment]
@mestia: thanks for the feedback. Hmm..that one is interesting, but I have to admit that I have a hard time figuring out what exactly is going on here. I mean I don't understand how your deb is being built, therefore I have a hard time to debug what can be the problem.

Based on the error message, I guess something is not imported in your files (`is_sudo()` is included in `Rex.pm`), but how could that happen in your case, and/or what do we miss in our test suite?

Maybe adding a `use Rex;` to `Rex::Commands::Rsync` would help, but even then we also would need to understand why it only seems to fail in your case.

**Comment by mestia** [comment]
@ferki: thank you for looking on it. I'll check what could be wrong with the tests. Right now I am closing the issue.

**Comment by ferki** [comment]
@mestia: thanks for the feedback, and that you take care of the issue status! ;) Feel free to reopen it or open a new one if needed.

ps.: you probably have noticed already, but 1.3.3 has just been released last week ;)

**Comment by mestia** [comment]
Yes, I have noticed it, just had a very busy week, I hope the next week I'll have enough time to check it out.
