### ISSUE TITLE
Installing from CPAN fails with missing dependencies

### ISSUE THREAD

**Issue by stiron** [RexOps/Rex#771]
Hello,

Installing Rex from CPAN is failing due to missing dependencies.

OS: CentOS 7
Perl: 5.20.2

2 dependencies missing (XML::Simple,XML::LibXML); additionally test harness failed
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports FERKI/Rex-1.3.2.tar.gz
Failed during this command:
 SHLOMIF/XML-LibXML-2.0121.tar.gz             : writemakefile NO -- No 'Makefile' created

 (optional) MIKEM/Net-SSLeay-1.70.tar.gz      : make NO
 (optional) SULLR/IO-Socket-SSL-2.017.tar.gz  : make_test NO
 TODDR/XML-Parser-2.44.tar.gz                 : make NO
 BJOERN/XML-SAX-Expat-0.51.tar.gz             : make_test NO one dependency not OK (XML::Parser); additionally test harness failed
 GRANTM/XML-Simple-2.20.tar.gz                : make_test NO one dependency not OK (XML::SAX::Expat)
 FERKI/Rex-1.3.2.tar.gz                       : make_test NO 2 dependencies missing (XML::Simple,XML::LibXML); additionally test harness failed

Cheers,
Tamas

**Comment by ferki** [comment]
@stiron: thanks for the report! But, _dude_, Rex does [list those as dependencies on CPAN](https://metacpan.org/source/FERKI/Rex-1.3.2/Makefile.PL), and they are deps for quite a while now. Can it be that XML::Simple and XML::LibXML just simply cannot be built on CentOS 7 and/or onoyour machine for some reason?

**Comment by stiron** [comment]
I think I ran into the same problem with the system perls of CentOS 7 and Ubuntu 14.04. CPAN and cpanm compiles all of the dependencies and install them without these three.

**Comment by eskaaren** [comment]
I can confirm that I have Rex running on CentOS 7 without problems.

Do you have libxml2 installed via yum?

**Comment by ferki** [comment]
So `XML::Parser` needs `Expat` installed, and `XML::LibXML` needs `libxml2` installed to be built - both of which is out of the scope what CPAN clients can install on a machine (would need bundling, building from source, or installing via the OS's package manager). The respective build systems of the dependencies print out what they need, as they ar expected.

I'm gonna close this for now, as it doesn't seem to be a Rex bug, or something that is solvable on Rex side. Feel free to reopen though, if needed!
