### ISSUE TITLE
Links in Rex::Commands "COMMANDLIST" section broken

### ISSUE THREAD

**Issue by ehuelsmann** [RexOps/Rex#776]
On the website, the links in the "COMMANDSLIST" section on http://www.rexify.org/api/Rex/Commands.pm.html do nothing when I click on them (Chrome, latest).

**Comment by ferki** [comment]
@ehuelsmann: good catch, thanks for reporting! :)

**Comment by ferki** [comment]
Fixed in the release-1.3.3 branch.
