### ISSUE TITLE
Can't locate IO/String.pm in @INC  when using Rex::Commands::Augeas

### ISSUE THREAD

**Issue by petersonchen** [RexOps/Rex#806]
Hi Rex Team , 

I use Rex V1.2.1 , 
when using Rex::Commands::Augeas  in my Rexfile and run will output below message :

Can't locate IO/String.pm in @INC (@INC contains: CODE(0x20ad398) 

Is this dependency module required  to install ?

**Comment by ferki** [comment]
Yes, `IO::String` is a dependency, and I just checked on CPAN that it was already a [dependency for 1.2.1](https://metacpan.org/pod/release/JFRIED/Rex-1.2.1/lib/Rex.pm). How did you install rex-1.2.1? Can you reinstall it to see if that pulls in the dependency this time?

**Comment by petersonchen** [comment]
@ferki 

I use rex on CentOS 6 , I followed  http://www.rexify.org/get.html  to install rex rex-1.2.1


$ rpm --import https://rex.linux-files.org/RPM-GPG-KEY-REXIFY-REPO.CENTOS6
$ cat >/etc/yum.repos.d/rex.repo <<EOF
[rex]
name=Fedora \$releasever - \$basearch - Rex Repository
baseurl=https://rex.linux-files.org/CentOS/\$releasever/rex/\$basearch/
enabled=1
EOF
$ yum install rex

**Comment by ferki** [comment]
I believe this has been fixed by https://github.com/RexOps/rex-build/commit/fcb61111a529a768e2b336a0d154df8d1a78868c, and packages built after that should state `IO::String` as a dependency.

Sorry for the delay, and feel free reopen RexOps/rex-build#17 if needed.
