### ISSUE TITLE
Rex/Args.pm: Undefined subroutine call

### ISSUE THREAD

**Issue by patricklauer** [RexOps/Rex#828]
At current git HEAD / commit e5733eab22d64aa9127afdd30765a4d67bbc039e:

```
$ rex -t
Undefined subroutine &Rex::Args::Dumper called at /home/patrick/perl5/lib/perl5/Rex/Args.pm line 101, <> line 8.
```
Ok, it's kinda my fault for giving nonsensical input, but that looks like broken code :)

**Comment by ferki** [comment]
Fixed on #847.
