### ISSUE TITLE
Rex::Test module should allow setting parameters for VMs

### ISSUE THREAD

**Issue by patricklauer** [RexOps/Rex#829]
A problem we ran into a few times now is that the default KVM template generates a VM with 256MB memory. This makes it easy to have tests OOM.
We have a local workaround that pokes libvirt directly and reboots the test VM with larger memory limit. But this is just a workaround and not a nice solution.

It would be nice to be able to set at least some of the parameters directly, possibly syntax would be:
`my $t = Rex::Test->new(name => 'testvm', memory => '512000', cores => '2');`

**Comment by ferki** [comment]
This has been fixed in 1.4.0 via #839.
