### ISSUE TITLE
alternative storage disk for kvm

### ISSUE THREAD

**Issue by Prajithp** [RexOps/Rex#832]
Is there any way to set alternative storage path for kvm?

 right now kvm images are creating under the /root/storage/ and  I would like to change this to /vm/images. 

Here goes my sample Rexfile
```
use Rex -feature => ['0.57'];

use Rex::Commands::Box init_file => "box.yml";

user "root";

group kvm_server => '192.168.1.200';

auth for => "kvm_server" => 
  user => 'root',
  password => 'xxxx';

task "create_vm", group => "kvm_server", sub {
  boxes "init";
};

task setup_vm => sub {
  pkg [ "wget", "nginx" ],
    ensure => "latest";
};
````

**Comment by krimdomu** [comment]
hi @Prajithp ,
i'm sorry but this is currently not possible. The path is currently hardcoded here: https://github.com/RexOps/Rex/blob/374bfd48e62406021b1a158fe67f72df2f1cde65/lib/Rex/Virtualization/LibVirt/import.pm#L39

But this would be easy to change.

**Comment by ferki** [comment]
@Prajithp: until then symlinking might help as a quick and easy workaround- at least that's what I do when I quickly need to do the same.

**Comment by Prajithp** [comment]
@krimdomu  Thank you so much for the clarification.

@ferki Yes, symlinking seems to be the good  idea. But, I have already modified both Box/Base.pm and Virtualization/LibVirt/import.pm to use custom storage path. Please check the below diff.

```
--- ./Virtualization/LibVirt/import.pm  2015-09-04 13:41:22.000000000 +0530
+++ /root/import.pm     2015-11-16 16:23:04.508120837 +0530
@@ -36,9 +36,16 @@
 
   my $dir = dirname $opt{file};
   my ( undef, undef, $suffix ) = fileparse( $opt{file}, qr{\.[^.]*} );
-  my $file = "storage/" . $dom . $suffix;
-  mkdir "./storage";
+  my $storage_path;
+  if ( $opt{storage_path} ) {
+   $storage_path =  $opt{storage_path};
+  }
+  else {
+   $storage_path = "./storage/";
+  }
 
+  my $file = $dom . $suffix;
+  mkdir $storage_path;
   my $format = "qcow2";
 
   my @serial_devices;
@@ -53,7 +60,7 @@
     my @vmdk = grep { m/\.vmdk$/ } i_run "tar -C $dir -vxf $opt{file}";
 
     Rex::Logger::debug(
-      "converting $cwd/tmp/$vmdk[0] -> $cwd/storage/$file.qcow2");
+      "converting $cwd/tmp/$vmdk[0] -> $storage_path/$file.qcow2");
     i_run "qemu-img convert -O qcow2 $cwd/tmp/$vmdk[0] $cwd/$file.qcow2";
 
     if ( $? != 0 ) {
@@ -103,11 +110,12 @@
     }
   }
 
+  warn("$storage_path/$file");
   Rex::Virtualization::LibVirt::create->execute(
     $dom,
     storage => [
       {
-        file        => "$cwd/$file",
+        file        => "$storage_path/$file",
         dev         => "vda",
         driver_type => $format,
       },
```
```
--- Box/Base.pm 2015-09-04 13:41:22.000000000 +0530
+++ /root/Base.pm       2015-11-16 16:23:53.315897151 +0530
@@ -86,6 +86,10 @@
   $self->{name} = $name;
 }
 
+sub storage {
+  my ( $self, $name ) = @_;
+  $self->{storage_path} = $name;
+}
 =head2 setup(@tasks)
 
 Sets the tasks that should be executed as soon as the VM is available through SSH.
```

**Comment by ferki** [comment]
It's a bit harder to review copy-pasted patches than pull requests, but I think I only have one question at first glance. What is this new line's purpose?
```perl
  warn("$storage_path/$file");
```

**Comment by krimdomu** [comment]
This is only a debug output. warn() is like print() but print on stderr.

**Comment by ferki** [comment]
@krimdomu: I know what it does ;) I was just wondering why exactly is it there? :)

I was thinking like:
>That seems like a debugging output, so I guess we should print it using Rex::Logger. Hmm..I'm not sure if this is included only by mistake as a leftover from development-time debugging, or because of a real intent of printing out the path.

At that point, my question trigger fired, and just asked :)

Also, the POD seems to be missing for `Rex::Box::Base::storage`.

All those are very minor and we can clean up with a follow-up commit, or it can be fixed just before merging.

@Prajithp: it looks good in general, thanks! Are you considering to send a PR we can merge, or should we just take your patch and apply it (with the minor fixes from above)?

**Comment by Prajithp** [comment]
@ferki Sure, I can send a pull request, that is not an issue.

 Regarding that 'warn', it was added for just a debugging purpose.

**Comment by Prajithp** [comment]
@ferki  @krimdomu  Created PR for this issue.
