### ISSUE TITLE
Unrecognized OS: OpenBSD 5.8

### ISSUE THREAD

**Issue by ferki** [RexOps/Rex#850]
According to the tweet of Neil McGuigan (‏@vancouverdata )

> rex 1.3.2 tries to load Rex/User/Linux.pm on OpenBSD 5.8

Currently Rex::User::Linux is the fallback user management module, so it looks like `lsb_release -s -i` and/or `uname -s` returns something weird on OpenBSD 5.8, which is unrecognized by `is_openbsd()` (i.e. not matching `qr{OpenBSD}i`).

**Comment by neilmcguigan** [comment]
Note: I am running OpenBSD 5.8 (i386) in VirtualBox 4.3.26

# lsb_release -s -i
(ksh: lsb_release: not found)

# uname -s
OpenBSD

I ran dump_system_information in Rex and got the following (some info elided):

$kernelversion = 'GENERIC#1066'
$kernelrelease = '5.8'
$operatingsystemrelease = '5.8'
$architecture = 'i386'
$kernel = 'OpenBSD'
$kernelname = 'OpenBSD'

Ran  `account "foo", home => "/home/foo"`  in Rex, got the following:

[2015-12-03 10:55:28] ERROR - Error executing task:
[2015-12-03 10:55:28] ERROR - Error getting user information for foo at C:/programs/strawberry-perl/perl/site/lib/Rex/User/Linux.pm line 348.

[2015-12-03 10:55:28] WARN - Error running task/batch: Error getting user information for foo at C:/programs/strawberry-perl/perl/site/lib/Rex/User/Linux.pm line 348.

[2015-12-03 10:55:29] INFO - Exiting Rex...
[2015-12-03 10:55:29] INFO - Cleaning up...

**Comment by ferki** [comment]
@neilmcguigan: I can't seem to reproduce this on linux with rex-1.3.2, using both Net::OpenSSH and, since you seem to run rex from windows, Net::SSH2 for connection. It can successfully detect a remote OpenBSD 5.8 system as OpenBSD, by falling back to the `uname -s` method, then it can successfully create and/or update users for me via calling `account`.

So I guess this is more likely a windows-specific issue, and my theory is it couldn't detect the remote operating system due to some failure in reading remote output.

Could you try with latest Net::SSH2 (0.58 as of this moment), and latest rex (1.4.0), please? Also, you should be able to see more details in the debug output (running with `rex -d ...`). If it still fails, please post the debug output to your favorite paste service and link it here for further inspection.

**Comment by ferki** [comment]
We couldn't reproduce this behavior, and haven't received additional information in the past years. Recent versions of Rex are passing tests on recent OpenBSD versions (6.6, 6.8), while OpenBSD 5.8 has reached its end-of-life on 2016-09-01. Also, OpenBSD support (including user management) has been improved via #1211 and #1213.

Based on the above, I'm closing this issue. Please open a new bug if it reappears, I'd be happy to debug and fix.
