### ISSUE TITLE
Rex::Args->get() is missing

### ISSUE THREAD

**Issue by krimdomu** [RexOps/Rex#860]
Due to some refactoring the `Rex::Args->get` method was removed. We need to readd it and return the current parameters of a task (or, in compatibility mode, return all parameters)

**Comment by kablamo** [comment]
Why is this needed?  I don't see it used anywhere.

**Comment by krimdomu** [comment]
This is true, but this is used, because there where no method to get the parameters inside a hook (for example `before`). So people who are needing the parameters their use this method.

**Comment by kablamo** [comment]
Ok makes sense.  I'll add it back.  I should also document the method and module since it something we are supporting.

**Comment by krimdomu** [comment]
This would be really cool
