### ISSUE TITLE
We should write down our deprecation policy

### ISSUE THREAD

**Issue by kablamo** [RexOps/Rex#861]
We already have a deprecation policy.  But I would like to write it down.  Its not clear to me what it is and where the exact boundaries are.  And if its not clear to me, then its probably not clear to users either.  It should be pretty short.  I can probably just add a paragraph to the README.  Also if we are going to put such an insane amount of effort into backwards compatibility we should advertise that as a feature

**Comment by ferki** [comment]
There's now an initial version of a more formal [deprecation policy](https://github.com/RexOps/Rex/wiki/Deprecation-policy) in the wiki. Provided the written format stays the same for a while, it can be later moved into the codebase as part of the documentation if needed.
