### ISSUE TITLE
add possibility for run command to pass parameters as array

### ISSUE THREAD

**Issue by krimdomu** [RexOps/Rex#872]
If someone want to execute a command with multiple parameters that contains spaces, quotes and other things it is always complicated for the user to find the right quoting.

So it would be good to have a possibility to pass the arguments as an array to the run command and let rex do the right quoting.

For example something like this:

```perl
run "su", [ "-c", "create user eloor with password 'eloor' ;" ];
```

**Comment by kentfredric** [comment]
Commentary from `#perl` is String::ShellQuote would be useful for this purpose: https://metacpan.org/pod/String::ShellQuote 

And in the view of one day working on windows, Win32::ShellQuote would be useful there: https://metacpan.org/pod/Win32::ShellQuote

**Comment by krimdomu** [comment]
@kentfredric many thanks for the modules, there is also a shellquoting module in Net::OpenSSH which we can use: https://metacpan.org/release/Net-OpenSSH

Lets see which of them fit best
