### ISSUE TITLE
summary tests are broken for 1.4rc

### ISSUE THREAD

**Issue by ferki** [RexOps/Rex#901]
Looks like tasks are returning unexpected exit codes, e.g. `ls asdfxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx` returns an exit code of `2` on the CLI, and the tests are expecting the same, but the task actually returns 1.

**Comment by ferki** [comment]
According to CPAN testers results, it's still failing for BSD/darwin systems. I believe rex is returning the correct exit code, but the exit code of the failing commands in the test are having different exit codes compared to linux systems.

**Comment by krimdomu** [comment]
yes, this is os dependant. maybe it is better to test if return code != 0
