### ISSUE TITLE
update_system on Debian ignores errors during apt-get update

### ISSUE THREAD

**Issue by abeverley** [RexOps/Rex#913]
This is not strictly speaking a bug with Rex, but it is something that I consider needs fixing by Rex. I am experiencing the problem here: http://unix.stackexchange.com/questions/175146/apt-get-update-exit-status

When ```apt-get update``` runs, it only warns on problems such as unable to get an updated index of a repo. This is a problem as you can think that your system is updating correctly, whereas it might not actually be pulling all the security updates, and failing silently.

I'd be happy to produce a patch, failing on warnings, in a similar manner to the link.

What do you think?

**Comment by krimdomu** [comment]
@abeverley i think this is a good idea.

@ferki what do you think?

**Comment by abeverley** [comment]
Hi guys, I'm keen to get this sorted. What do you think of this initial patch? Once I've got comments, I'll do a proper PR: https://github.com/abeverley/Rex/commit/c390d8189e130659c5ffec282ee4649e0f4e6f8f

Thanks, Andy

**Comment by krimdomu** [comment]
@abeverley i think this is a good idea. So feel free to create a pull request :+1:

**Comment by abeverley** [comment]
Brilliant, thanks @krimdomu . See #1059
