### ISSUE TITLE
Rex::Shared::Var is nearly undocumented

### ISSUE THREAD

**Issue by shattered** [RexOps/Rex#920]
There's a brief mention in http://rexify.org/docs/release_notes/0.29.html and some sample code in https://groups.google.com/d/msg/rex-users/_z0d7P0N31k/2jrf_hOPSncJ

**Comment by ferki** [comment]
Yeah, you're right, we should add proper POD and include it on the website too. Thanks!

**Comment by ferki** [comment]
@shattered: so there are now some initial documentation for `Rex::Shared::Var` in the `1.4rc` branch, will be released in the next RC (soon™). Thanks for the report.
