### ISSUE TITLE
Rex::Shared::Var::Array does not implement SHIFT

### ISSUE THREAD

**Issue by shattered** [RexOps/Rex#921]
I hit that one while trying to transform shared array into a hash (because of a different issue that prevents storing hash in shared hash).

**Comment by ferki** [comment]
> because of a different issue that prevents storing hash in shared hash

Can you maybe share some more details on this too? Feel free to open a separate issue, if you see fit.

**Comment by ferki** [comment]
It's probably a good idea to implement `unshift` and `pop` too.

**Comment by ferki** [comment]
@shattered: there's a PR (#1001) that adds `shift` for shared arrays if you'd like to do some early testing.

I couldn't reproduce your
> different issue that prevents storing hash in shared hash

If you still experience that, please open a new issue about the details. We have some basic tests for that feature at [t/shared.t#L21-L34](https://github.com/RexOps/Rex/blob/development/t/shared.t#L21-L34), but I'm happy to add more cases and fix bugs.

**Comment by shattered** [comment]
I've tested PR#1001 and it works for me, thanks.

"issue that prevents storing hash in shared hash" is actually a bit different in nature, I will try to submit a test case soon.

**Comment by krimdomu** [comment]
@shattered 
i also had the problem with storing a nested data structure in a shared variable just today. So i just opened an issue for that.
