### ISSUE TITLE
Rex::Interface::Exec::OpenSSH execute_line_based_operation is no line based operation anymore

### ISSUE THREAD

**Issue by krimdomu** [RexOps/Rex#951]
this can be seen with the tail command. The tail command sets the readbuffer to 1 byte and this code executes the line based operation for every byte.

**Comment by ferki** [comment]
I think `Rex::Interafce::Exec::Local` is affected too.

**Comment by ferki** [comment]
proposed fix: #953

**Comment by ferki** [comment]
It looks like it was already broken in 1.3.3, at least in my quick tests.
