### ISSUE TITLE
feature flag "tty" doesn't work with Net::OpenSSH anymore

### ISSUE THREAD

**Issue by krimdomu** [RexOps/Rex#957]
Somewhere in the IOReader.pm module there is a bug removing \r from the output.

This can be seen when running in debug mode. For example:

```
SSH/executing: /sbin/iptables^M-save
```

**Comment by krimdomu** [comment]
459a114 removes the newline(s) at the end. but this is not enough. it doesn't remove ^M in an multiline output.

**Comment by ferki** [comment]
Fixed on #958.
