### ISSUE TITLE
A couple of typos

### ISSUE THREAD

**Issue by mestia** [RexOps/Rex#969]
https://gist.githubusercontent.com/mestia/9076ec75567cd774cf4b/raw/12ae1432cd3ccefa2a1cfed4c5ddb64e68a6089c/spelling.patch

Thanks!

**Comment by mestia** [comment]
it appears that the typos are not actually fixed, since the patch successfully applies for rex-1.9.0.
The current patch from Debian: https://salsa.debian.org/perl-team/modules/packages/rex/-/blob/master/debian/patches/spelling.patch
Thanks!

**Comment by ferki** [comment]
@mestia: thanks for pinging here about it!

It was applied to the then-default `development` branch, but for some reason it was not merged back into the now-default `master` branch yet (please see #1265 for more context).

Rest assured, it will find its way there eventually, and will be part of a future release!

**Comment by ferki** [comment]
@mestia: as part of the porting efforts on #1265, I have now cherry-picked the original patch to the master branch.

I'd be happy to further reduce the packaging overhead. So if there are more changes you need to patch when packaging for Debian, please open an issue about them (and ideally, also send the patches as PRs :).
