### ISSUE TITLE
Test failures are not failing

### ISSUE THREAD

**Issue by patricklauer** [RexOps/Rex#989]
Tests are created as:
```
my $t = Rex::Test::Base->new;
```

```
not ok 65 - hosts.allow checksum is correct
#   Failed test 'hosts.allow checksum is correct'
#   at t/bootstrap.t line 95.
[...]
1..76
FAIL
[2016-03-09 17:53:22] <local> INFO - All tasks successful on all hosts
```
and 
```
$ echo $?
0
```
I would expect test failures to not be a success ... :)

**Comment by ferki** [comment]
I agree on rex needs to use a non-zero exit code in this case (this would make it easier to integrate with CI tools too).

On top of that, I'd say `Test:run` should be marked as failed task, and listed in the summary as such. The task being tested may or may not be failed, and that info is most probably useful for the task developer.

**Comment by krimdomu** [comment]
@ferki  for the summary message i have created a new task. this can be solved independently.

**Comment by ferki** [comment]
Great, thanks!
