### ISSUE TITLE
Rex doesn't recognize Manjaro

### ISSUE THREAD

**Issue by bissei** [RexOps/Rex#993]
Rex should recognize Manjaro as Arch clone

**Comment by krimdomu** [comment]
@bissei 
thanks for the info.

Could you please tell me what `lsb_release -s -i` output is?
and if there is a file `/etc/arch-release`? Or is there an other /etc/... file (like /etc/manjaro-release or something else that helps detecting manjaro)

**Comment by bissei** [comment]
Hi,

Here is results:
cat /etc/manjaro-release
Manjaro Linux

lsb_release -s -i
ManjaroLinux

command lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	15.12
Codename:	Capella

find  /etc/ -name '*-release' -print -exec cat {} \;
/etc/lsb-release
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=15.12
DISTRIB_CODENAME=Capella
DISTRIB_DESCRIPTION="Manjaro Linux"
/etc/os-release
NAME="Manjaro Linux"
ID=manjaro
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="1;32"
HOME_URL="http://www.manjaro.org/"
SUPPORT_URL="http://www.manjaro.org/"
BUG_REPORT_URL="http://bugs.manjaro.org/"
/etc/manjaro-release
Manjaro Linux


I hope this helps.
